### ISSUE TITLE
A "real" example of codeclimate.json

### ISSUE THREAD

**Issue by markbates** [codeclimate/test-reporter#12]
Can I get a real example of this file? The one in 
https://github.com/codeclimate/test-reporter/blob/master/DEVELOPERS.md is clearly a dummy one. I need to be able to figure out how some of the information is calculated and what it should be.

For example:

`"covered_strength": 1,` is that a `0-1` scale? How is that calculated?.

You get the idea.

**Comment by pbrisbin** [comment]
@markbates I believe this issue, as it is currently described, can be closed. I think you have a "real" example, and the payloads you're producing look accurate. Please create a new issue if there's still work to be done on this track.

I think it would be better if I can take on testing the uploads myself, but I need your help me with #21 and/or #22 to do that.
