### ISSUE TITLE
Send coverage as an array, not a string

### ISSUE THREAD

**Issue by ale7714** [codeclimate/test-reporter#120]
The payload generated by `format-coverage` has a `coverage` string that looks like `"[1, null, 0, null, 2]"`. Then on `upload-coverage` we parse that string back to array and the `coverage` being sent to the server doesn't have the `null`'s on it. 

Because we already update the server side to receive an array, the payload generated by `format-coverage`/`sum-coverage` should be an Array instead of a string. That way we would also avoid doing the conversion from string to array in the `upload-coverage` step.

**Comment by markbates** [comment]
First, can we break this into multiple tickets? There are multiple changes requested in this ticket. 

Second, in regards to the `total_with_blank_lines` change, not all of the formats offer blank, or not counted, lines information. Most, from what I've seen, only offer information on "Testable" lines. Right now all yes coverage, regardless of tool, is uniformed, this change will break that. Is that ok? @GordonDiggs

**Comment by ale7714** [comment]
@markbates yeah, sure it should be separated.  Moving `total_with_blank_lines` to a separate ticket.  Wasn't really aware that some tools didn't offered blank lines.

**Comment by ale7714** [comment]
@markbates i updated this ticket, to only be related to the bug. I suggested updating format-coverage to an array because i think it would make it easier. But if you think that fixing upload coverage so it sends properly the blank lines is easier. That would work too :).
