### ISSUE TITLE
source file coverage must be a string 

### ISSUE THREAD

**Issue by ale7714** [codeclimate/test-reporter#127]
Follow up to https://github.com/codeclimate/test-reporter/issues/124#issuecomment-299939688. 

Source file coverage array must be send to the endpoint as a `String` to prevent `rails` from removing `null` values.

**Comment by ale7714** [comment]
@markbates small question here should we keep https://github.com/codeclimate/test-reporter/blob/master/upload/source_files.go#L13 as type `Coverage` or as type string?

**Comment by markbates** [comment]
It should be kept as type `Coverage`. It gets converted to a `string` when it's marshaled to JSON here: https://github.com/codeclimate/test-reporter/blob/master/formatters/coverage.go#L18

**Comment by ale7714** [comment]
@markbates if i try `make test-simplecov` on master it looks like we're still sending an array.  So i was thinking it could be related to something like that or https://github.com/codeclimate/test-reporter/blob/master/upload/test_report.go#L34

**Comment by markbates** [comment]
it looks like we're using a *different* `Coverage` type there, that's why. Let me fix that.
