### ISSUE TITLE
Any way to use this with CodeShip Basic's ParallelCI?

### ISSUE THREAD

**Issue by andyw8** [codeclimate/test-reporter#132]
I'm using Codeship Basic with 2 pipelines for RSpec and one for Cucumber.

It seems CodeShip Basic lacks the requirement of "the ability to run commands after all tests have completed" when using multiple pipelines.

Is there any way around this?

**Comment by andyw8** [comment]
I got helpful reply from @whiteotter of Codeship about this:

> I think you've touched on the key difference between the Codecov tool and the Code Climate tool, in that the Codecov process self determines when it has received all the coverage reports. And there's unfortunately no way at this time to trigger an event to notify Code Climate that all pipelines have run successfully.
>
> You would need to build a service outside the Codeship ecosystem. Perhaps something that receives a final command from each pipeline, notifying of its completion (including the delivery of the coverage report to Code Climate). You'd have to maintain a correct accounting of the number of pipelines for a given project, but this is one feasible workaround.

**Comment by pbrisbin** [comment]
Hi @andyw8, sorry for the delay here.

It is possible to do a similar sort of thing with the `cc-test-reporter` tool. The `sum-coverage` sub-command takes a `--parts` flag which indicates how many files you expect it to sum. If it sees fewer than those, it errors. That means you could *attempt* to do this at the end of both pipelines and expect whichever finished last to succeed.

I would try something like the following in both pipelines:

```sh
bundle exec rake rspec # or cucumber
cc-test-reporter format-coverage --output coverage/codeclimate.rspec.json # or cucumber.json
aws s3 sync ./coverage/ "s3://your-bucket.aws.amazon.com/coverage/$SHA"

# I *think* sync is two-way, but if not run it again to pull down
#aws s3 sync "s3://your-bucket.aws.amazon.com/coverage/$SHA" ./coverage/

if cc-test-reporter sum-coverage --parts 2 coverage/codeclimate.*.json; then
  cc-test-reporter upload-coverage
fi
```

**Comment by andyw8** [comment]
Thanks @pbrisbin, I'll give that a try.

**Comment by pbrisbin** [comment]
I'm going to make this Closed. Feel free to re-open if you're still having trouble.

**Comment by antoniosb** [comment]
If you're using AWS S3 to store partial coverages, you can check on both pipelines if all necessary coverage parts are present, before trying to sum it up.

something like:

```bash
if [ `aws s3 ls s3://<bucket_name/coverage/$CI_BUILD_NUMBER/ | grep <coverage_part> | wc -l` == $PARTS ]; then
  # sync remote bucket with local folder
  # consolidate all coverages and send to to codeclimate
fi
```
