### ISSUE TITLE
Avoid calling git on upload-coverage/sum-coverage

### ISSUE THREAD

**Issue by ale7714** [codeclimate/test-reporter#157]
upload-coverage/sum-coverage should get all the info from the input file(s) and avoid calling git. Those commands can be run on a container where the git repo is not present anymore.

I  beleilve that the issue is coming from [here](https://github.com/codeclimate/test-reporter/blob/master/formatters/report.go#L81) that calls `env.New()`. I think we don't need to get the `env.gitInfo()` on the case upload-coverage/sum-coverage.

cc @GordonDiggs

**Comment by ale7714** [comment]
@maxjacobson if everything behaves correctly i would close this issue. WDYT?

**Comment by maxjacobson** [comment]
👍 works for me
