### ISSUE TITLE
sum-coverage null+0 behavior

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/test-reporter#158]
`sum-coverage` currently expects that a file's coverage information in any individual payload will either be present and accurate, or missing. Under this assumption, the elements in each `coverage` array are currently combined with the following rules:

```
# Numbers take precedence over nulls
sum_element(null, b) = b
sum_element(a, null) = a
sum_element(a, b) = a + b
```

If using a feature like [SimpleCov's `track_files`](http://www.rubydoc.info/gems/simplecov/SimpleCov/Configuration:track_files), this assumption is not true. Coverage information may be present and accurate, missing, or _an artificial `0`_.

This has the bad behavior of converting any _actual_ `null` coverage elements to `0`s when summed, decreasing overall covered percent.

We are considering changing the rules to this:

```
# Nulls take precedence over numbers
sum_element(null, b) = null
sum_element(a, null) = null
sum_element(a, b) = a + b
```

I think changing this behavior, to work specifically for the known SimpleCov case, won't negatively impact the general case because a sum operation where one side is `null` and the other not is incoherent to begin with: it's saying one payload declares the line as source code and the other does not. What is and is not a line of source code should not change depending on which tests ran. (Ignoring any kind of meta-programming craziness.)

Given incoherent input, we are free to resolve it however we like (provided we are consistent and document it), so we might as well make it work for the (only) known case where this will occur: the "all `0`s" case caused by `track_files`.

/cc @noahd1 @ale7714

**Comment by noahd1** [comment]
That's my feeling at the moment. This is hard to change. The other option is to keep today's default and provide a summing strategy.

**Comment by noahd1** [comment]
(Accidental close)

**Comment by noahd1** [comment]
(Also a premature submission) 

I noted that this is hard to change because changing default would inexplicably change coverage numbers without a clear "break"

**Comment by pbrisbin** [comment]
My vote is it's fine to change because:

1. This scenario is a very infrequent edge case (possibly never, beyond this example which is demonstrably broken)
1. There are very few people besides us using this reporter now
1. It's pre-1.0

**Comment by noahd1** [comment]
Ok think this is actionable.
