### ISSUE TITLE
sum-coverage --output -

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/test-reporter#168]
Running `sum-coverage --output -` creates a file called `-`; such an invocation should output to `stdout`.

I've found this bug before on other sub-commands. I wonder if there's a way to centralize handling of a file-path option along with this fix so all the path flags behave correctly with regards to a `-` argument as `stdout`/`stdin`.

**Comment by ale7714** [comment]
tried it and it's fixed :)
