### ISSUE TITLE
409 Error response

### ISSUE THREAD

**Issue by masa-iwasaki** [codeclimate/test-reporter#179]
I tried new coverage reporter today and got 409 errors. I paste a partial console log on CircleCI.

```
Coverage report generated for RSpec to /home/ubuntu/Qualizm/coverage. 5559 / 7701 LOC (72.19%) covered.
Error: response from https://api.codeclimate.com/v1/test_reports was 409
Usage:
  cc-test-reporter after-build [flags]

Flags:
  -s, --batch-size int               batch size for source files (default 500)
  -e, --coverage-endpoint string     endpoint to upload coverage information to (default "https://api.codeclimate.com/v1/test_reports")
  -t, --coverage-input-type string   type of input source to use [simplecov, lcov, coverage.py, clover, gocov]
      --exit-code int                exit code of the test run
  -r, --id string                    reporter identifier (default "8799629dfaae158c4e5a0c9489f188723bdff733309a737b0db106a230f11e4c")
  -p, --prefix string                the root directory where the coverage analysis was performed (default "/home/ubuntu/Qualizm")

Global Flags:
  -d, --debug   run in debug mode


bin/rspec --fail-fast --color --require spec_helper --format=progress --format=Nc --format=RspecJunitFormatter --out ${CIRCLE_TEST_REPORTS}/rspec/rspec.xml --order rand spec/models ; cc-test-reporter after-build --exit-code $? returned exit code 255
```

The first line shows SimpleCov had finishes successfully. So the error log will be caused by test reporter. And the last line shows the executed command line.

**Comment by ale7714** [comment]
hi @masa-iwasaki, thank you for trying out the new test-reporter. A 409 response from API means that we have created a test-report for that particular commit SHA. Did you retry your CI build?

Please, can you push a commit and check if test-reporter finish successfully?

**Comment by masa-iwasaki** [comment]
hi @ale7714.

I pushed a new commit but still got same errors.

**Comment by ale7714** [comment]
@masa-iwasaki can you share the error here? 
Also can you try running `cc-test-reporter after-build --exit-code $?` with the `--debug` flag so you we can have more details. 
Thanks.

**Comment by masa-iwasaki** [comment]
@ale7714 I ran  the command with `--debug` option. But the log contains filenames in our private repo. Can I send it privately on your help page at https://codeclimate.com/help ?  I will close this issue if we can do that.

**Comment by ale7714** [comment]
@masa-iwasaki of course. Please write us through the help page. It would be great if you include this issue link for reference. Thanks again for trying out the test reporter.

**Comment by masa-iwasaki** [comment]
OK. I submitted a request for customer support. I will close this ticket. Thanks for your help !
