### ISSUE TITLE
Working example for parallel reporting from Solano CI

### ISSUE THREAD

**Issue by oboxodo** [codeclimate/test-reporter#181]
Reporting this here in case you want to include some [working example for a parallel build from Solano CI](https://gist.github.com/oboxodo/9571987ea6841c0854f49a916d65c613).

This one is a bit more complex to include it all in the `solano.yml` file but you might still want to try.

Happy to receive feedback to simplify it.

**Comment by pbrisbin** [comment]
Thanks so much for putting this together! We would almost certainly like to incorporate this content either into the README or our main docs site; do we have your permission to copy, modify, and use it in that way?

**Comment by oboxodo** [comment]
Be my guest! I'm sure you can optimize it so I'm eager for feedback.

BTW, I tried a shorter version by embedding all the commands in `solano.yml`, but it didn't work because Solano started throwing warnings saying `pre_setup`, `post_worker` and `post_build` should be strings. So apparently they don't support yaml lists in those hooks?

**Comment by oboxodo** [comment]
Also, please note that env var `SOLANO_WORKER_NUM` is *undocumented*. I found it by inspecting solano's environment with `printenv | grep -i "TDD\|SOLANO\|TEST\|WORK\|ID\|CI"` in those scripts and looking at the logs.

According to their docs I expected to be able to use `TDDIUM_TID` but that one always returned `0` so workers were overwriting each other's report.

**Comment by davehenton** [comment]
@oboxodo Thanks so much for this info! We've added your example to our help docs [here](https://docs.codeclimate.com/docs/setting-up-test-coverage#section-ci-examples).

**Comment by pbrisbin** [comment]
Thanks @davehenton, with those added there I'm going to close this Issue.
