### ISSUE TITLE
Display success message on STDOUT when successful

### ISSUE THREAD

**Issue by professorNim** [codeclimate/test-reporter#183]
On error there is obviously output displayed, but on success there is no output sent to STDOUT. Are we to assume no output means everything succeeded? I know there is a debug runtime option that is more verbose, and the exit code status which should be 0, but maybe it would be nice to see a simple "Success!" message printed? Just my 2 cents...

**Comment by ale7714** [comment]
@professorNim thanks for trying out the new test reporter. The exit code is only 0 when command is successful but we will be adding a more verbose message.

**Comment by professorNim** [comment]
@ale7714 good to know. I like the new test reporter, one less dependency in my app, and no frozen dependencies too!
