### ISSUE TITLE
Submitting repeated commit report should be idempotent

### ISSUE THREAD

**Issue by oboxodo** [codeclimate/test-reporter#192]
I'm using the scripts reported in #181 (which you incorporated in your [docs](https://docs.codeclimate.com/docs/setting-up-test-coverage#section-ci-examples)) with Solano CI. But I'm having a problem.

Sometimes the CI ends up running a build for the same commit. This could be either because we manually triggered a new build or because of a fast-forward merge or because of some other reason.

But the build will be considered failed because `cc-test-reporter` is returning an error when we attempt to upload the coverage report. This is the error:

```
Error: response from https://api.codeclimate.com/v1/test_reports.
HTTP 409: A test report for commit f4014287c1624ae09d9008a78bd6f343912b976d already exists
```

I understand your system might want to reject a repeated report... but I don't have a way to know from the CI environment if a report for this commit has already been uploaded to CodeClimate. I could save some file with the SHA as name in S3 after uploading and check for its existence before uploading, but... that's a nasty workaround.

I actually think that the uploader should keep reporting the 409 code, but the exit status should be 0 (zero) and the command execution be considered success. The end goal is to upload a coverage report for that commit. If you already have it, then it's success anyway.

That said, I think you should also replace your previous report with the newer one. There's a chance your customers might've uploaded a report with some old simplecov settings, then regenerated using a new configuration and want to overwrite the already sent report for the same commit. But this is an optional new feature request.

I think the important thing here is to make the report upload idempotent if you already have a report for the same commit. This is not an edge case. It's pretty normal to have more than one build per commit.

**Comment by lleger** [comment]
I ran into this as well. Rebuilding on CI caused a 409 which failed the build. I agree with @oboxodo — reporting a 409 is fine as long as the command passes. This will make sure the build still passes.

**Comment by lleger** [comment]
FWIW, for now I’m running this on CI to keep the build from failing.

```bash
./cc-test-reporter after-build --exit-code $? || true
```

**Comment by bethesque** [comment]
+1 for this.

**Comment by taiidani** [comment]
Ditto here. I had this particular quirk hit me painfully when rerunning an already successful multi-stage build on CircleCI 2. It really shouldn't fail if run a second time -- CI/CD runners do that all the time.

**Comment by sullerandras** [comment]
I think adding a `|| true` is a dirty workaround because that silences all codeclimate errors, so you will never notice if it stopped working for some reason (which is likely since it's in a beta stage).
I hope the codeclimate team will come up with a real solution soon.

**Comment by lflux** [comment]
We ran into this as well when creating a [Concourse](https://concourse.ci) resource, [codeclimate-resource](https://github.com/lflux/codeclimate-resource), for CodeClimate. It would help at the very least to have a distinct exit code, or possibly a CLI flag to ignore 409's.

**Comment by aurule** [comment]
We've run into this same deficiency. A fix is apparently not in the near-term roadmap, according to an email from Dave at Code Climate, which is disappointing.

**Comment by katwchen** [comment]
Hi everyone, 
We will start working on a fix for this next week. Should have something out in a few weeks. 
Thank you for your feedback and patience!

**Comment by katwchen** [comment]
Hi everyone, 

Thanks for your feedback, we've made an adjustment to this. 
Now, if we submit test reports from multiple builds for the same commit SHA, we will give you a 409 "conflict when uploading" error, but the exit code is 0.

**Comment by oboxodo** [comment]
Just FTR, https://github.com/codeclimate/test-reporter/pull/268 seems to be the PR with the code changes for this.

Thanks!

**Comment by bethesque** [comment]
Awesome!
