### ISSUE TITLE
-bash: cc-test-reporter: command not found

### ISSUE THREAD

**Issue by SeriouslyAwesome** [codeclimate/test-reporter#193]
Hey gang, excited to try this new test coverage reporter on Circle CI (with parallel builds)! Ran into an issue following your guides [here](https://docs.codeclimate.com/docs/setting-up-test-coverage#section-ci-examples).

The pre-test step `cc-test-reporter before-build` fails with the message `-bash: cc-test-reporter: command not found`, despite following the guidelines verbatim. I ran `curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter` and `chmod +x ./cc-test-reporter` locally and got the same result.

**Comment by chrishulton** [comment]
Hey, sorry for the delay, I did not see this issue earlier.

Are you still experiencing this problem?  We have a darwin package available as well at `https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64` that might be useful depending on your architecture.  

Otherwise, I'm not sure what might be causing this.  Does anything seem off with your `$PATH`?  Can you run other bash commands, just not test-reporter?

**Comment by wfleming** [comment]
This might be a simple PATH issue with our CircleCI guide: since we recommend writing the binary to `./cc-test-reporter`, and `.` probably isn't in the `PATH`. The fix may be to change the steps executing the binary to run `./cc-test-reporter`? e.g.

```yaml
test:
  pre:
    - ./cc-test-reporter before-build
  override:
    - bundle exec rspec; ./cc-test-reporter after-build --exit-code $?
```

**Comment by ale7714** [comment]
@wfleming that's exactly it.

**Comment by SeriouslyAwesome** [comment]
Thanks @wfleming I'll give that a shot and report back.

**Comment by SeriouslyAwesome** [comment]
@chrishulton @wfleming's suggestion worked. Calling `./cc-test-reporter before-build` works as expected. I'm having other issues configuring it for parallel tests, but I nothing I can't resolve by reading the docs and a little experimentation. Thanks all!

**Comment by hass-laughingman** [comment]
Hi Sorry to open this again, but I'm getting the same issue.
I have a docker image built on `ruby:2.4.1-alpine`
I tried adding the location of `cc-test-reporter` to PATH but still getting
`sh: cc-test-reporter: not found`
