### ISSUE TITLE
Anaconda Packages

### ISSUE THREAD

**Issue by andreas-h** [codeclimate/test-reporter#225]
It would be great if you could build and upload conda packages for this repo to anaconda.org. conda is a common way to build Python packages and it would be very convenient to have the test reporter installable via conda.

**Comment by maxjacobson** [comment]
Hi @andreas-h 

Right now, we support one way of installing the test-reporter:

```shell
curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
chmod +x ./cc-test-reporter
```

What are the advantages of distributing it via conda as well?

**Comment by andreas-h** [comment]
Thanks for your answer, @maxjacobson !  With conda, the user wouldn't have to remember a URL  and could just do `conda install cc-test-reporter`.  However, since the main purpose is automated use, and nobody wants to do that manually anyways, it's no problem putting those two lines into the script.
Sorry for the noise ..

**Comment by maxjacobson** [comment]
👍 thanks for the idea - if we introduce future distribution channels in the future, we'll consider conda, and now it's in our minds :)
