### ISSUE TITLE
Prefix not being honoured in after-build

### ISSUE THREAD

**Issue by andrewmichaelsmith** [codeclimate/test-reporter#227]
Perhaps I misunderstood something here, but I expected the uploader to find my `coverage.xml` in `/tmp`.

Running from a project dir (not /tmp):

```
~/proj $ ./cc-test-reporter -d after-build --prefix /tmp/ --coverage-input-type coverage.py
DEBU[0000] about to run format-coverage                 
DEBU[0000] using formatter coverage.py                  
DEBU[0000] checking search path  for coverage.py formatter 
DEBU[0000] checking search path coverage.xml for coverage.py formatter 
ERRO[0000] could not find coverage file 
```

```
ls -latr /tmp | grep cov
-rw-r--r--  1 10000 10000 63818 Sep 26 10:24 .coverage
-rw-rw-r--  1 andy  andy      5 Sep 26 10:32 coverage.xml
```

And if we strace it (going off the `stat`), it does indeed only appear to be looking in the cwd:

```
 strace ./cc-test-reporter -d after-build --prefix /tmp/ --coverage-input-type coverage.py 2>&1 | grep xml
write(2, "time=\"2017-09-26T11:12:04+01:00\""..., 112time="2017-09-26T11:12:04+01:00" level=debug msg="checking search path coverage.xml for coverage.py formatter" 
stat("coverage.xml", 0xc420126788)      = -1 ENOENT (No such file or directory)
write(2, "time=\"2017-09-26T11:12:04+01:00\""..., 175time="2017-09-26T11:12:04+01:00" level=error msg="could not find coverage file \ncould not find any files in search paths for coverage.py. search paths were: , coverage.xml" 
write(2, "Error: could not find any files "..., 99Error: could not find any files in search paths for coverage.py. search paths were: , coverage.xml
```

**Comment by dblandin** [comment]
Hey @andrewmichaelsmith,

The `-p|--prefix` option is meant to override the root directory of your source code. This defaults to the CWD. For example, if your source code is at `/home/user/src/project` then the default `prefix` would be `/home/user/src/project`. We use this to translate absolute file paths in the report to project-relative file paths.

Overriding this is useful when you run a test suite within a docker container but submit the test coverage report on the host machine.

It sounds like you might be fine with the default `prefix` but want to point the test-reporter to an alternate test coverage report path in `/tmp`.

You can do that by dropping down to the `format-coverage` and `upload-coverage` commands:

```bash
$ cc-test-reporter format-coverage --coverage-input-type covearge.py < /tmp/coverage.xml
$ cc-test-reporter upload-coverage --id <cc-reporter-id>
``` 

The `cc-test-reporter` binary has some `-h|--help` documentation for the reporter and its subcommands that you might find useful as well.

Let me know if that works out!

**Comment by andrewmichaelsmith** [comment]
Apologies, I should have verified this before closing (I actually came up with an alternative solution - but have since found that doesn't work but your solution looked sound).

I can't seem to get your trick working:

```
$ ./cc-test-reporter format-coverage --input-type coverage.py < /tmp/coverage.xml
ERRO[0000] could not find coverage file 
could not find any files in search paths for coverage.py. search paths were: , coverage.xml 
Error: could not find any files in search paths for coverage.py. search paths were: , coverage.xml
```

Any ideas?

**Comment by dblandin** [comment]
Hey @andrewmichaelsmith,

Can you try a positional argument instead? We might need to look into the stdin support.

```
$ ./cc-test-reporter format-coverage --input-type coverage.py /tmp/coverage.xml
```

**Comment by mackbrowne** [comment]
@dblandin 

I'm having the same issue.  My coverage report is in a folder in the root of the project at '.coverage/lcov.info'

I tried 

```
./cc-test-reporter after-build -t lcov --exit-code 0 < ~/repo/.coverage/lcov.info
```

And

```
./cc-test-reporter after-build -t lcov --exit-code 0 < .coverage/lcov.info
```

Neither worked.  The only way i can get it to work is if the folder is 'coverage' without the dot.  AKA the default place it's looking for it.

**Comment by mackbrowne** [comment]
got it working, heres what i needed to do

```
      - run: ./cc-test-reporter format-coverage -t lcov .coverage/lcov.info
      - run: ./cc-test-reporter upload-coverage
```

**Comment by dblandin** [comment]
@mackbrowne Yep, that looks good to me 👍 

Sorry for the confusion. I don't think we support the `< .coverage/lcov.info` stdin style.

**Comment by perrosen** [comment]
Awesome. Just what i was looking for. Thanks!

This would be great to have better documentation around since the use case of test output being in another folder than root must be quite common. Had to find this solution by going through the github issues.

**Comment by shimaamarzouk** [comment]
in my case I wasn't having any rspec tests and also no coverage. So I just created one test and then all passed
