### ISSUE TITLE
Semaphore CI JavaScript Example

### ISSUE THREAD

**Issue by juliancoleman** [codeclimate/test-reporter#228]
I'm looking for instructions on how to set up the `test-reporter` with Semaphore CI. I'm a bit new to the CC ecosystem, and I'm unfamiliar on how this is supposed to work in a CI without a config file, unlike Circle CI or Travis.

I have most of the reporter working, but it looks like it requires an `--exit-code` of type `int`. What values are being expected here? `$?` may not always be the case as you can never guarantee the return value of the previously run command will still be available in memory. Equally important, Semaphore returns a `"passed"` or `"failed"`, which is bound to the `SEMAPHORE_THREAD_RESULT` environment variable. How can this result be translated to work with `test-reporter`?

**Comment by juliancoleman** [comment]
I answered my own question, so I'll post the configuration below...

### Step 1 - Setup

using yarn or npm, run the following

```sh
# yarn
yarn add -D istanbul mocha # co-mocha if necessary
yarn add lcov-parse

# npm
npm i --save-dev istanbul mocha # co-mocha if necessary
npm i -S lcov-parse
```

### Step2 - Script

add the following script to the `scripts` section of your `package.json`. I recommend calling the script `coverage`, or something similar for semantics.

```sh
istanbul cover --report lcov _mocha
```

### Step 3 - Semaphore

add the following environment variable via __Project Settings -> Environment Variables__

Name: `CODECLIMATE_REPO_TOKEN`
Content: `YOUR_CODECLIMATE_REPO_TOKEN`
Encrypt content: _leave unchecked_

You can find your repo token by heading over to Code Climate, and navigating to __Settings -> Test coverage__, Your Code Climate repo token is also known as the `TEST REPORTER ID`.

### Step 4 - Build settings

#### Setup

```
yarn
```

#### Job 1

```
yarn coverage
```

#### After job

```
npm i -g codeclimate-test-reporter
```
```
codeclimate-test-reporter < ./coverage/lcov.info
```

### Code Climate

Head back over to your repo in Code Climate, and your score should be available from the repo __Overview__

**Comment by ale7714** [comment]
@juliancoleman 👋 thank you for your interest in Code Climate and our test reporter.

I'm glad that you have a solution but it's using the old test reporter. So i wanted to help you with a few tweaks to get our new test reporter properly setup on `Semaphore CI`.

```bash

# Setup phase 

# setup cc-test-reporter
curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
chmod +x ./cc-test-reporter
./cc-test-reporter before-build
export CC_TEST_REPORTER_ID=<TEST REPORTER ID from your Repo>

# After job 
exitcode=$(if [ "$SEMAPHORE_THREAD_RESULT" == "passed" ]; then 0; else 1; fi)
./cc-test-reporter after-build --exit-code $exitcode
```

You don't need 
```
npm i -g codeclimate-test-reporter
codeclimate-test-reporter < ./coverage/lcov.info
``` 

And you can remove CODECLIMATE_REPO_TOKEN as well. 

Let me know if you have any questions about the example above. I'm happy to help!

I'll also talk with our CX team and discuss adding an example for the new test reporter on Semaphore CI on our docs.

**Comment by juliancoleman** [comment]
Thank you so much for the detailed instructions, @ale7714 . I'll work on reconfiguring this weekend and I'll get back to this issue when I have success on it.

**Comment by juliancoleman** [comment]
@ale7714 I'm getting the following error: `bash: 0: command not found`. Should we wrap those in quotations?

**Comment by ale7714** [comment]
@juliancoleman do you know which command are you getting this error from?

**Comment by juliancoleman** [comment]
I'm getting it from the `$SEMAPHORE_THREAD_RESULT`. It's coming from `then 0; else 1; fi;`

**Comment by ale7714** [comment]
@juliancoleman oh, i miss an `echo` before the 0 and 1
so the command should be:
```
exitcode=$(if [ "$SEMAPHORE_THREAD_RESULT" == "passed" ]; then echo 0; else echo 1; fi)
```

sorry for the confusion 😅

**Comment by juliancoleman** [comment]
That works! I didn't know how `echo` was going to work with a variable assignment.. anyway, one final error on that last command...

```
Error: could not find any viable formatter. available formatters: simplecov, lcov, coverage.py, clover, gocov, gcov, cobertura, jacoco
```

**Comment by ale7714** [comment]
@juliancoleman please, can you add the `--debug` flag to `after-build`?. Like this:
```
./cc-test-reporter after-build --exit-code $exitcode --debug
```
And paste the output here.

**Comment by juliancoleman** [comment]
```
DEBU[0000] about to run format-coverage                 
DEBU[0000] searching for a formatter to use             
DEBU[0000] checking simplecov formatter                 
DEBU[0000] checking search path coverage/.resultset.json for simplecov formatter 
DEBU[0000] checking gocov formatter                     
DEBU[0000] checking search path c.out for gocov formatter 
DEBU[0000] checking cobertura formatter                 
DEBU[0000] checking search path cobertura.xml for cobertura formatter 
DEBU[0000] checking search path cobertura.ser for cobertura formatter 
DEBU[0000] checking jacoco formatter                    
DEBU[0000] checking search path jacoco.xml for jacoco formatter 
DEBU[0000] checking lcov formatter                      
DEBU[0000] checking search path coverage/lcov.info for lcov formatter 
DEBU[0000] checking coverage.py formatter               
DEBU[0000] checking search path coverage.xml for coverage.py formatter 
DEBU[0000] checking clover formatter                    
DEBU[0000] checking search path build/logs/clover.xml for clover formatter 
DEBU[0000] checking search path clover.xml for clover formatter 
DEBU[0000] checking gcov formatter                      
DEBU[0000] checking search path ./ for GCov formatter   
Error: could not find any viable formatter. available formatters: simplecov, lcov, coverage.py, clover, gocov, gcov, cobertura, jacoco
Usage:
  cc-test-reporter after-build [flags]

Flags:
  -s, --batch-size int               batch size for source files (default 500)
  -e, --coverage-endpoint string     endpoint to upload coverage information to (default "https://api.codeclimate.com/v1/test_reports")
  -t, --coverage-input-type string   type of input source to use [simplecov, lcov, coverage.py, clover, gocov, gcov, cobertura, jacoco]
      --exit-code int                exit code of the test run
  -r, --id string                    reporter identifier (default "c0e37a3239394e767e3b3cd3f6d47bd290a8b9d3dcdeda8183a7662b5a1db4b9")
  -p, --prefix string                the root directory where the coverage analysis was performed (default "/home/runner/index-by-key")

Global Flags:
  -d, --debug   run in debug mode
```

**Comment by ale7714** [comment]
@juliancoleman is your lcov output under `coverage/lcov.info`? if you run cat `coverage/lcov.info` before running `after-build` are you able to see the output of your lcov.info file?

**Comment by juliancoleman** [comment]
I'm actually not running lcov. one second

**Comment by juliancoleman** [comment]
okay, so I'm using `istanbul cover --report lcov _mocha` and all seems to be working!

**Comment by juliancoleman** [comment]
![screenshot-20171012112013-1106x458](https://user-images.githubusercontent.com/11545939/31512338-5fb47058-af3f-11e7-9498-85ba45c313be.png)
![screenshot-20171012112102-168x100](https://user-images.githubusercontent.com/11545939/31512351-769218e8-af3f-11e7-8974-fc0a73f61439.png)


nice.

**Comment by ale7714** [comment]
@juliancoleman 🎉  nice! thanks for trying out the new test reporter. Glad that everything is working. Any other questions? or can I close this issue?

**Comment by juliancoleman** [comment]
We can close this issue :+1:

**Comment by stefanahman** [comment]
Based on: https://semaphoreci.com/docs/failed-build-reported-as-passed.html

This should work: `./cc-test-reporter after-build --exit-code $?`

**Comment by juliancoleman** [comment]
@stefanahman this issue has been closed for months...

**Comment by stefanahman** [comment]
I know. Just wanted to share my findings about "$?" variable instead on defining your own "exitcode" (as seen in the picture).

**Comment by codeodor** [comment]
When using the example at https://docs.codeclimate.com/docs/semaphore-ci-test-coverage-example on the after job item, I noticed the screen shot does not match the copy-able text. Also, using that text resulted in an error, as if `$exitcode` is blank:

`Error: flag needs an argument: --exit-code`

@stefanahman's comment got it working for me, so thanks!
