### ISSUE TITLE
Rename format/upload commands

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/test-reporter#23]
Noticed this while looking at the testing harness:

The commands are `format-coverage` and `upload-coverage`. The reporter will some day deal in more than just coverage, and there may be other things to format and certainly more things to upload, so we need to make sure our low-level names are specific enough.

**Comment by markbates** [comment]
We can put them under a `coverage` sub command if you'd prefer that:

```
$ cc-test-reporter coverage format
$ cc-test-reporter coverage upload
```

It's up to you.
