### ISSUE TITLE
Source paths not respected in coverage.py format

### ISSUE THREAD

**Issue by jmcarp** [codeclimate/test-reporter#237]
I'm generating a coverage report with `pytest` like this:

```
pytest --cov mypackage --cov-report xml
```

But `after-build` fails with

```
Error: open __init__.py: no such file or directory
```

It looks like this is happening because file paths within `packages` are relative to the path in `sources`, which doesn't appear to be used here. I can work around this by changing to the `mypackage` directory before running `after-build`, but it would be more intuitive if I could run `after-build` without changing paths.

If you'd be interested, I'd be happy to write a patch that adds support for coverage.py `sources`.

**Comment by ale7714** [comment]
@jmcarp 👋  sorry on the late response. Thank you for trying out the new test reporter and your feedback. Recently we made a new release of the test reporter [v0.3.2](https://github.com/codeclimate/test-reporter/blob/master/CHANGELOG.md#v032-2017-10-30) that I think will address the issue you're having. Can you try it and let us know how it goes?

**Comment by dblandin** [comment]
Going to go ahead and close this issue. Let us know if this is not resolved!
