### ISSUE TITLE
The test reporter file goes away due to site maintenance 

### ISSUE THREAD

**Issue by mrrsm** [codeclimate/test-reporter#239]
We had multiple builds fail because the site that the curl request points to was down for maintenance.  Can the files for the test reporter be served from a different location to prevent this from happening?

**Comment by dblandin** [comment]
Hey @mrrsm!

Thank you for the issue. You raise a great point!

We're internally discussing methods to keep resources like the test-reporter binaries available during our maintenance windows.

While this will allow your builds to format and sum test coverage reports, our API will still be unavailable and unable to receive or process test reports.

If you wanted to guard against that, you could add `|| true` to your `after-build` or `upload-coverage` invocation.

Next steps for us would be to return a 503 from api when down for maintenance and have the test-reporter output a warning message. Would it make sense to exit 0 in that case?

Another improvement would be to continue to receive test reports and process them later once we're out of maintenance, but that'll take some planning, time, and prioritization.

**Comment by mrrsm** [comment]
We are using the enterprise edition so having the api's go down is not an issue for us.
We were running into the same issue as #192 and fixed that with the `|| true`.  That made doing the curl request the important piece.  Once there is a stable build tagged I could get around this by managing a single binary per CI server.

I can't really put my finger on if queueing would be useful or not, it sounds like it would be in some scenarios though we would have to run at least the CodeClimate build once the server came back up.

**Comment by GordonDiggs** [comment]
Hey @mrrsm I just deployed a change so that the test reporter will remain available while we are down for maintenance! Going to close this issue
