### ISSUE TITLE
Beta testers

### ISSUE THREAD

**Issue by jmgarnier** [codeclimate/test-reporter#24]
Hi,

I heard about this project when I asked on twitter if there will be a feature in Code Climate to merge coverage reports when using parallel jobs in Travis. 

Would you mind updating this issue when this project is ready for beta testing?

I was watching on gh but it seems that you are still busy 😉 

Cheers,

Jean-Michel

**Comment by GordonDiggs** [comment]
@jmgarnier Yep we will be sure to reach out when we have something ready! Out of curiosity - which language(s) are you interested in using for the reporter?

**Comment by jmgarnier** [comment]
@GordonDiggs Thanks for the quick reply. I am interested in Ruby. We have a (private) Rails 4.2 app and our tests spawn in 5 different jobs on Travis CI.

**Comment by GordonDiggs** [comment]
@jmgarnier Thanks! We are prioritizing end-to-end Ruby support as an alpha so I will definitely let you know when that is available

**Comment by paultwo** [comment]
Hi @GordonDiggs -- commenting so I can follow this thread. We're eagerly awaiting this as well 👍

**Comment by GordonDiggs** [comment]
@jmgarnier @paultwo Hi there! This reporter is now available! There are directions in the README. I'm going to close this issue, but if you run into any problems please open new issues!
