### ISSUE TITLE
github.com/Sirupsen/logrus import needs to be updated

### ISSUE THREAD

**Issue by albertyw** [codeclimate/test-reporter#240]
"Sirupsen" updated his username to be "sirupsen" so dependencies on any of his libraries, particularly logrus should be updated to the new path.

**Comment by toddmazierski** [comment]
Thanks for the heads up, @albertyw!

For the purposes of fetching, GitHub usernames aren't case-sensitive, so `dep ensure` still works as expected.

There are [many changes](https://github.com/sirupsen/logrus/compare/v0.8.7...v1.0.0) between the version of Logrus we're currently using (`v0.8.7`) and the version where the renamed username became "official" (`v1.0.0`). We don't have a compelling reason to upgrade this library right at this moment (ex. new features, bugs, etc.), but we'll upgrade once we do.

**Comment by wfleming** [comment]
Closing since this does not affect the current version or how we are managing our dependencies yet.
