### ISSUE TITLE
Failed to find jacoco.xml

### ISSUE THREAD

**Issue by ham1** [codeclimate/test-reporter#259]
We have a Maven project which creates a jacoco.xml file in `target/site/jacoco/` but when running `./cc-test-reporter after-build` it says

> Error: not find any viable formatter. available formatters: simplecov, lcov, coverage.py, clover, gocov, gcov, cobertura, jacoco

Running with `./cc-test-reporter after-build -d -t jacoco` gives:
> DEBU[0000] about to run format-coverage                 
DEBU[0000] using formatter jacoco                       
DEBU[0000] checking search path  for jacoco formatter   
DEBU[0000] checking search path jacoco.xml for jacoco formatter 
ERRO[0000] could not find coverage file 
could not find any files in search paths for jacoco. search paths were: , jacoco.xml 
Error: could not find any files in search paths for jacoco. search paths were: , jacoco.xml

Please see here for our project: https://github.com/Frameworkium/frameworkium-core
and a the error in CI:
https://travis-ci.org/Frameworkium/frameworkium-core/builds/302599922

**Comment by ham1** [comment]
The project dir structure after a test run looks like:

```
tree -d -L 2
.
├── doc
│   └── style
├── logs
├── src
│   ├── main
│   └── test
└── target
    ├── classes
    ├── generated-sources
    ├── generated-test-sources
    ├── maven-status
    ├── site
    ├── surefire-reports
    └── test-classes
```

**Comment by pomle** [comment]
We have this problem too. I managed to get around it by copying the `jacoco.xml` file from `./target/site/jacoco/jacoco.xml` to `./src/main/java/jacoco.xml` and then running `cc-test-reporter` from inside `./src/main/java/`.

The CLI help for `cc-test-reporter` looks like you can give it PATH prefixes but I could not get any of them to work.

Obviously this is not a nice solution but could be helpful while this tool matures.

**Comment by ham1** [comment]
Thanks for the workaround, it would be nice to have this fixed, unless I'm doing something wrong?

**Comment by magneticflux-** [comment]
@ham1 I'm having the same issue. For reference, here's my project: https://github.com/magneticflux-/kotlin-simplexml-rss/pull/1.

**Comment by zubri** [comment]
Same problem here with a Gradle project at Jenkins. Solved it with this other workaround:

> cd src/main/java
> test-reporter-latest-linux-amd64 format-coverage -t jacoco ../../../build/reports/jacoco/test/jacocoTestReport.xml
> test-reporter-latest-linux-amd64 upload-coverage -r ID

It would be nice to have the format-coverage and upload-coverage documented in the help, along with the prefix option fixed.

PD: Does anyone know what's the purpose of the before-build command?

**Comment by rucindrea** [comment]
I have the same problem using a java project. I tried the workaround from @pomle bu I am still stuck: 

When I run the test reported from within my `./src/main/java` folder,  `cc-test-reporter` complains that it doesn't find the `/MyJavaClass.java` file. So it seems it's using the  `/` prefix for the source files, and I cannot change that with the `-p` flag

**Comment by toddmazierski** [comment]
Hi all,

We've released version [v0.5.1](https://github.com/codeclimate/test-reporter/blob/master/CHANGELOG.md#v051-2018-03-19) of the Test Reporter, which includes a fix for this bug. It's similar to the workarounds shared by @pomle and @magneticflux (thank you), but without having to manually move files around.

## Usage

Instead of `after-build`, please use these two sub-commands:

1. `format-coverage`, which has 2 important settings:

    * **`JACOCO_SOURCE_PATH`**: the path to Java source files (a new environment variable)
    * **`coverage file`**: to path to JaCoCo coverage XML file (the first argument)

2. `upload-coverage`

## Example

```
JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter \
  format-coverage target/site/jacoco/jacoco.xml     \
  --input-type jacoco
./cc-test-reporter upload-coverage
```

## Feedback

Please let me know on this ticket if you have success with this workaround, questions, or any other feedback. Thanks for your patience.

**Comment by rucindrea** [comment]
This fix worked for me, thanks a lot for the help! I'm now able to upload the Jacoco coverage files with no issues.

**Comment by efueger** [comment]
Great! Thanks for the confirmation @rucindrea. I'll go ahead and close this out.

- For anyone else who ran into this (@ham1 @zubri @magneticflux- @pomle)  
- let us know if you have any trouble using the new sub-commands. 

Thanks again for your help getting to the bottom of this. 👌 

---

PS: @zubri - here's more info about [`before-build`](https://github.com/codeclimate/test-reporter/issues/260#issuecomment-369783913)

**Comment by magno32** [comment]
How does this fix help with multi module builds?

**Comment by efueger** [comment]
@zubri -

- Were you able to get PR coverage working with your Jenkins setup? 
- If so, can you tell me how you configured your branch/pr names?

**Comment by AndreaAdvanon** [comment]
What if there are multiple `JACOCO_SOURCE_PATH`s? For example in a multi module gradle project?

**Comment by khatkarr** [comment]
@toddmazierski what if there are multiple Java modules in the project and many main files.

**Comment by veb1994** [comment]
I had the same issue. The problem was in path to files. In tutorials and docs it seems they consider "app" directory to be current working directoty. But in fact it's root of the project. So after I've added "app" to paths in my configs, it works fine.

You can check my project to understand: https://github.com/veb1994/java-project-71

Also a part of my main.yml

- name: Make code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: **_app/_**src/main/java
        with:
          debug: true
          coverageCommand: make **_-C app_** report
          coverageLocations: ${{github.workspace}}**_/app_**/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
