### ISSUE TITLE
What does the `before-build` command do?

### ISSUE THREAD

**Issue by zanona** [codeclimate/test-reporter#260]
Sorry guys, but

> To be run before a build

Is way too obscure 😜

**Comment by bmulholland** [comment]
The CircleCI 2.0 multiple suite example doesn't even use it: https://github.com/codeclimate/test-reporter/blob/master/examples/multiple_suites.md

Maybe because it literally does nothing: https://github.com/codeclimate/test-reporter/blob/master/cmd/before-build.go#L11

**Comment by maxjacobson** [comment]
:wave: how's it going?

I work at Code Climate, and I also did not know why we have that :sweat_smile:. Clicking through from that file, to the PR that added it, to [the issue that requested it](https://github.com/codeclimate/test-reporter/issues/59#issue-216059741), it seems the answer is: you're right, and right now it does nothing, but in a later version of the test-reporter, it may do something. I don't know that we have a concrete plan for what that thing is (probably not if it hasn't come up in about a year).

But, let's say we come up with  :sparkles: _Amazing Feature X_ :sparkles: , but it requires tracking some metadata about your repository before the build starts. It would be very annoying to have to go back and update your CI configs for all of your repositories! One nice thing about this design is that you're always pulling the latest version of the test-reporter, so when :sparkles:  _Amazing Feature X_ :sparkles:  comes down the pike, you won't have to do anything at all to turn it on.

Thanks for the head's up that we're not including that in our examples! I'll ping our docs team about it.
