### ISSUE TITLE
after-build: allow for multiple coverage reports

### ISSUE THREAD

**Issue by tkrotoff** [codeclimate/test-reporter#263]
When running `./cc-test-reporter after-build` would be nice to be able to specify multiple coverage reports.
Currently `--prefix` option only takes 1 path instead of multiple.

Use case: a "monorepo" with [Lerna](https://github.com/lerna/lerna). In such scenario you have multiple packages/projects inside the same Git repository and each of them have its own coverage report.

Examples: https://github.com/tkrotoff/react-form-with-constraints/tree/master/packages

**Comment by ale7714** [comment]
👋 @tkrotoff, thank you for trying out the new `test-reporter`.  `after-build` is intended to be use with a single build. For multiple test suites we recommend using the low level commands `format-coverage`, `sum-coverage` and `upload-coverage`. A small example can be found on the [README](https://github.com/codeclimate/test-reporter#multiple-suites).
Let us know if you have any other question.

**Comment by tkrotoff** [comment]
With these low level commands I have to run an extra step within each package and not only inside [`.travis.yml`](https://github.com/tkrotoff/react-form-with-constraints/blob/master/.travis.yml).
Beside the extra work, cc-test-reporter is not an npm package but a binary. So now inside my code I have to compile cc-test-reporter for each platform I support (Windows, MacOS, Linux).

This is just not possible, codeclimate related things should stay within the CI otherwise it becomes too complex.
FYI codecov automatically detects I have several coverage reports: https://travis-ci.org/tkrotoff/react-form-with-constraints/builds/306974746#L1247

**Comment by ale7714** [comment]
@tkrotoff I think your feedback could be a great enhancement for the test-reporter. But on the meantime I did a quick attempt on how to setup the `test-reporter` to report multiple coverage reports on this [PR](https://github.com/tkrotoff/react-form-with-constraints/pull/19/files). 
If you want to try out on your repo update the `CC_TEST_REPORTER_ID` to the ID of your repo. Let me know what do you think about it. 

PS: I'll bring this feedback to the team so we can discuss internally, if any update comes up we'll update the issue.

**Comment by ale7714** [comment]
@tkrotoff also wanted to ask you about
> So now inside my code I have to compile cc-test-reporter for each platform I support (Windows, MacOS, Linux).

Sorry, I’m not sure I understand the problem. Please, can you explain more? It should be enough to use the `test-reporter` on the CI (in your case Travis).

**Comment by tkrotoff** [comment]
> I’m not sure I understand the problem

Forget that, my mistake.
Thanks a lot for the PR! it works fine: https://codeclimate.com/github/tkrotoff/ReactFormWithConstraints

I've specified CC_TEST_REPORTER_ID directly inside Travis CI configuration

I see several improvements:
- Add your PR as a README.md example 
- In the future: one command line that takes an array of coverage paths and if nothing is specified it detects coverage paths (like codecov.io [does](https://travis-ci.org/tkrotoff/react-form-with-constraints/builds/307864959#L800)) - so users don't have to deal with format-coverage loop, sum-coverage and upload-coverage
- I've renamed my GitHub repository from ReactFormWithConstraints to react-form-with-constraints (to match the npm package name...) and Code Climate still displays the old name (ReactFormWithConstraints) and refers to the old GitHub URL (it works because GitHub does a HTTP 301 Moved Permanently), https://codeclimate.com/github/tkrotoff/react-form-with-constraints gives a 404

**Comment by ale7714** [comment]
@tkrotoff Thank you for your comments. I wanted to lead you know that I updated you repo on Code Climate to point to https://codeclimate.com/github/tkrotoff/react-form-with-constraints. I'll pass along your feedback to the team. And if any question comes up don't hesitate to contact us again.
