### ISSUE TITLE
Setting for max coverage drop

### ISSUE THREAD

**Issue by darrenleeweber** [codeclimate/test-reporter#271]
For ruby, SimpleCov has a max coverage drop setting.  We want to fail a build only when the total coverage drops by 1%, we don't care about anything less than that [1].  There is no option on the code-climate web UI or elsewhere to set a similar threshold; it fails travis.ci builds when coverage drops by -0.1% but we just don't care about that.  We've decided to turn it off to avoid these false build failures.

[1] https://github.com/sul-dlss/sul_pub/pull/541

**Comment by ale7714** [comment]
@darrenleeweber Hi! Thank you for using Code Climate. Under your Repo -> Settings, you can enable or disable sending pass/fail statuses on your total coverage. 
Also you can configure the threshold on `diff-coverage` (lines changed by your PR). You can read more about it on our docs [here](https://docs.codeclimate.com/v1.0/docs/configuring-your-analysis#section-test-coverage).

Currently, we don't offer a threshold option for `total-coverage`. But I suggest disabling `total-coverage` status and increasing `diff-coverage` threshold to a percentage you feel comfortable with. This way you can make sure that all new/changed code meets with the coverage standard you expect. 

Let me know if there's anything else I can help with
