### ISSUE TITLE
Failing since 21.12.

### ISSUE THREAD

**Issue by tarlepp** [codeclimate/test-reporter#281]
I have been seeing following on my TravisCI output since 21.12.

`
$ if [[ $COVERAGE == true ]]; then php ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT fi
/home/travis/.travis/job_stages: eval: line 58: syntax error: unexpected end of file
`

Before it was working just like expected.

**Comment by maxjacobson** [comment]
Hi @tarlepp.

Hm.

Do you mind sharing the pertinent parts of your `.travis.yml`?

One thing that jumps out from that error message is `php`. The `cc-test-reporter` program isn't a php program, but a static binary that can be invoked like `./cc-test-reporter` rather than `php ./cc-test-reporter`.

**Comment by tarlepp** [comment]
@maxjacobson oh nice spot of that wrong command call - Will try again with fixed command.

**Comment by tarlepp** [comment]
@maxjacobson and yep that was the error - thanks!

**Comment by maxjacobson** [comment]
Sweet, glad to be of help. Happy new year
