### ISSUE TITLE
Error: bufio.Scanner: token too long

### ISSUE THREAD

**Issue by pkopac** [codeclimate/test-reporter#282]
I've just tried support for coverage. It didn't work. It seems like reading of files is broken.
The same happens on localhost and on Travis CI. I've tested the latest version (0.4.0).

See eg. https://travis-ci.org/chartmogul/chartmogul-go

```bash
gocov test -v -timeout=10m ./... > c.out
# ID given by env. variable
$ ./cc-test-reporter after-build -t gocov --exit-code 0
```

```
Error: bufio.Scanner: token too long
```
Size of `c.out`: 67K

Alternatively, for a smaller project I get:
```
Error: bad mode line: {"Packages":[{"Name":"github.com/...
(full file follows)
Usage: (help text follows)
```
Size of `c.out`: 19K

The files are one-liner outputs from `gocov test`.
I've checked the line ends are unix LF.

**Comment by nzin** [comment]
I found the @pkopac : when you run `gocov test` (from https://github.com/axw/gocov): gocov test [args...] will run go test [args...] with an implicit -coverprofile added, and then output the result of gocov convert with the profile.

The solution?
`gocov test ./... -coverprofile=c.out`

**Comment by nzin** [comment]
well I managed to make it working once, but not anymore. still investigating on my side... but this is a output format for sure

**Comment by pkopac** [comment]
@nzin: thanks for the reply, but the problem isn't in the gocov itself. It's in this app, the file seems to be whole on one line and the app tries to load the whole one line - into a too small buffer, I think.

**Comment by ale7714** [comment]
@pkopac 👋  sorry for the late reply. Could share with us your `c.out` file? If you don't want to share it over here, you could also send it over our support form in https://codeclimate.com/help. 

Also @nzin feel free to share the issue are you encountering with us either over here or directly with support. 

Hope we can get things working soon 😃

**Comment by nzin** [comment]
Hi,
Yes I have the exact same problem than @pkopac 
ie I try to run `gocov test ./... > c.out` on my (public) repo https://github.com/nzin/dctycoon.
The thing is, gocov create a file in json format. And `cc-test-reporter` is expecting a *non* json format (I think), more like what `go test . -coverprofile=c.out` outputs.

**Comment by nzin** [comment]
I guess we have to follow this code snippet (see https://stackoverflow.com/questions/45776043/codeclimate-test-coverage-formatter-for-golang#45776499):
```
for pkg in $(go list ./... | grep -v vendor); do
    go test -coverprofile=$(echo $pkg | tr / -).cover $pkg
done
echo "mode: set" > c.out
grep -h -v "^mode:" ./*.cover >> c.out
rm -f *.cover

./cc-test-reporter after-build
```

**Comment by pkopac** [comment]
@ale7714: no problem. You can generate it using the commands I've sent and the library I mentioned:
https://github.com/chartmogul/chartmogul-go

@nzin: Thank you! This works reliably. It seems like they can parse that format without a problem.

**Comment by ale7714** [comment]
@nzin thanks for pointing out a solution!
@pkopac  The `test-reporter` parses the `c.out` format and then uploads that to Code Climate. 

How do you feel about adding an example to the repo, similar to this https://github.com/codeclimate/test-reporter/blob/master/examples/python_examples.md#example-1? 

I think having a working example would be useful for other users.

**Comment by ale7714** [comment]
Actually, a PR was open by @bbqtd with a working example 🎉  https://github.com/codeclimate/test-reporter/pull/283. Worth also taking a look at! :)

**Comment by nzin** [comment]
I check the PR, I didn't know we can do the way around aka
`go test -coverprofile c.out ./...`
Looks interesting!

**Comment by nzin** [comment]
I commented the #283 PR, I think the solution he proposes is not working all the time. i.e. the one suggested above is IMHO working better.

**Comment by ale7714** [comment]
@nzin @pkopac I'm gonna go ahead and close this issue since we have a couple of solutions. But leave a comment if we need to re-open it. Also if you think is worth adding [this solution](https://github.com/codeclimate/test-reporter/issues/282#issuecomment-357558280) as an example, feel free to open a PR. I personally think that having mutiple solutions is always valuable.
