### ISSUE TITLE
Ruby format-coverage

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/test-reporter#29]
As a Ruby developer, I can convert SimpleCov results to the defined Code Climate format, so that I can sum and/or upload it later.

## Acceptance Criteria

- [x] I get something reasonable from `cc-test-reporter format-coverage --help` (or `help`, `-h`, whatever)
- [x] After running the test suite ruby project which generates SimpleCov coverage, I can run `cc-test-reporter format-coverage` and it produces `coverage/codeclimate.json` in the right format
- [ ] After running the test suites of a ruby project using different [named tests](https://github.com/colszowka/simplecov#test-suite-names), I can run `cc-test-reporter format-coverage` to produce a valid payload
- [x] `cc-test-reporter format-coverage` supports `--output -` to output to `stdout`
- [x] The payload includes information from the [documented](./blob/master/man/cc-test-reporter-format-coverage.1.md) environment variables

## Relevant Links

- [Payload format](./DEVELOPERS.md#coverage-payload)

**Comment by pbrisbin** [comment]
## Good

- Payload looks generally good
- `--output PATH` worked

## Bugs

- File was created as `codeclimate.json`, not `coverage/codeclimate.json`
- `--output -` created the file `./-`, didn't go to `stdout`
- `CI_BUILD_ID=42 cc-test-reporter format-coverage` didn't include `ci_services.build_identifier: "42"`

## Untested

- Different named tests
- `--help`

**Comment by pbrisbin** [comment]
Not accepted, created Issues for bugs found. Please let me know when this is ready again.

**Comment by markbates** [comment]
Once #44 is merged this will be ready for review again.

**Comment by markbates** [comment]
Ready for review again.

**Comment by pbrisbin** [comment]
I captured #45, but will Accept this anyway. We can prioritize that fix in a different milestone.
