### ISSUE TITLE
golang + jenkins + cover setup

### ISSUE THREAD

**Issue by sayanee** [codeclimate/test-reporter#299]
I have been trying to setup codeclimate with golang and `Jenkinsfile`, but was unable to find any examples.

I have referred to these resources already:

- [Configuring Test Coverage](https://docs.codeclimate.com/docs/configuring-test-coverage#section-ci-examples)
- [Jenkins test coverage](https://docs.codeclimate.com/docs/jenkins)
- [Golang examples](https://github.com/codeclimate/test-reporter/blob/master/examples/go_examples.md)

I am already running the test through Jenkins CI with `go test ./... -cover`. Any clue to the `Jenkinsfile`? Thanks a bunch 🙇‍♀️

**Comment by davehenton** [comment]
Hey @sayanee, thanks for reaching out. To help troubleshoot, could you open up a support ticket [here](codeclimate.com/help), including the following info:

- Repo name
- If you use single, parallel or multi-suite builds
- A copy of your CI configuration file
- Output from your CI when using the `--debug` flag in your CI configuration (`after-build --debug` for single builds, `format-coverage --debug` and `upload-coverage --debug` for parallel builds).
- Any relevant screenshots of your setup

Send that over when you get a chance, and we'll be happy to take a closer look. Thanks!

**Comment by davehenton** [comment]
Hey @sayanee, were you able to get this resolved? If not, please write into [support](https://codeclimate.com/help) with the information listed above, and we'll help get this sorted out. I'll close out this issue for now.

**Comment by sayanee** [comment]
Thanks @davehenton! Yes I was able to solve it. For the benefit of others stumbling on similar issue, here's a sample code:

### In `Makefile`

```sh
PACKAGES = $(shell find . -name '*.go' -exec dirname {} \; | sort --unique)

test:
	echo "mode: set" > c.out
	$(foreach pkg,$(PACKAGES),\
		echo > covsingle.out && \
		go test $(pkg) -coverprofile=covsingle.out -covermode=set && \
		tail -n +2 covsingle.out >> c.out || exit;)
	rm covsingle.out
```

### In `Jenkinsfile`

```sh
...
stages {
    stage("Running tests"){
      steps {
        echo "Running tests"
        sh "cc-test-reporter before-build"
        sh "make test"
        sh "cc-test-reporter after-build --insecure"
      }
    }
...
```
