### ISSUE TITLE
Error: unknown shorthand flag: 'c' in -coverprofile=c.out

### ISSUE THREAD

**Issue by jsamr** [codeclimate/test-reporter#301]
## Issue

When executing this command :
```bash
./cc-test-reporter after-build -t go test -coverprofile=c.out
```

The following error is printed :
```bash
Error: unknown shorthand flag: 'c' in -coverprofile=c.out
```

I just used the snippets provided as example here : [example/golang.md](https://github.com/codeclimate/test-reporter/blob/e12db9e4e5fa97d8c0019f2794d46aa7f6c1ca8b/examples/go_examples.md)

## Versions

- Go master version
- test-reporter versions 0.4.2 and 0.4.3 (latest)

## Travis Biild

[See this travis build](https://travis-ci.org/cmdse/core/builds/341731570)

## Travis.YML

<details>
  <summary>.travis.yml</summary>

```
language: go

# The coverprofile for multiple packages works in go 1.10
# see https://tip.golang.org/doc/go1.10#test
go:
  - master

env:
  - DEP_VERSION="0.4.1" CC_TEST_REPORTER="0.4.2"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-${CC_TEST_REPORTER}-linux-amd64 > ./cc-test-reporter
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep
  - chmod +x ./cc-test-reporter

install:
  - dep ensure

before_script:
  - ./cc-test-reporter before-build

script:
  - go test -coverprofile c.out ./...

after_script:
  - ./cc-test-reporter after-build -t go test -coverprofile=c.out --exit-code $TRAVIS_TEST_RESULT

```

</details>

**Comment by catkins** [comment]
I'm also seeing this issue - I can't seem to find a valid value for the `-t` flag. I followed the second example, which concatenates the .out files from the different packages.

```
Error: could not find any viable formatter. available formatters: clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, simplecov
```

**Comment by ale7714** [comment]
@jsamr @catkins Hi! I'm sorry for the confusion just updated our examples. `-t` (`--coverage-input-type`) is use to Identify the input type (format) of the COVERAGE_FILE.  So passing `go test -coverprofile=c.out` to this flag wouldn't be correct. In the case of Go, the correct value would be `gocov`. Although. using `-t` is optional and if you're storing the result of coverage under `c.out` the `test-reporter` would be able to find the file. So you can do: 

```
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
```

Again sorry for any confusion and let me know if I can help with anything.

**Comment by jsamr** [comment]
@ale7714 It works, thank you very much for your responsiveness !
Cheers,
JR
