### ISSUE TITLE
Coverage report sent successfully, but results do not appear in CC

### ISSUE THREAD

**Issue by mkautto** [codeclimate/test-reporter#308]
I am trying to integrate Travis CI and Code Climate. We have a NodeJS application with a lcov-format coverage report. The test-reporter debug output looks ok and it says that the coverage report was uploaded successfully: [Travis build with debug output](https://travis-ci.org/codento/rytmi-api/builds/343310818) 

However, the results do not show up in Code Climate. If I take a look at the test report using the Code Climate REST API, I get the following responses:

*GET https://api.codeclimate.com/v1/repos/:repo_id/test_reports/:test_report_id*
```
{
    "data": {
        "attributes": {
            "commit_sha": "3121dc73389f052385d9c6de186dd5029740c1b8",
            "committed_at": "2018-02-19T10:53:32.000Z",
            "covered_percent": 83.56164383561644,
            "rating": {
                "letter": "B",
                "measure": {
                    "unit": "percent",
                    "value": 83.56164383561644
                },
                "path": "/",
                "pillar": "Test Coverage"
            },
            "state": "invalid"
        },
        "id": "5a8aad3f689f6523a80009c2",
        "type": "test_reports"
    }
}
```

*GET https://api.codeclimate.com/v1/repos/:repo_id/test_reports/:test_report_id/test_file_reports*
```
{
    "data": [],
    "links": {}
}
```

**Comment by davehenton** [comment]
Hey @mkautto -- just opened up PR to your repo [here](https://github.com/codento/rytmi-api/pulls) with a solution. Once you take a look at that, can you let me know if that gets you up and running?

**Comment by mkautto** [comment]
Hello @davehenton, the PR fixed the problem for us. Thank you very much!
