### ISSUE TITLE
sum-coverage

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/test-reporter#31]
When I've generated multiple payloads from multiple (partial) test-suite runs, I want to combine (sum) them into a single payload, so I can upload it to Code Climate.

## Acceptance Criteria

We've used this in our parallel test builds for codeclimate/app and the summed coverage is reported and accurate.

**Comment by pbrisbin** [comment]
Shouldn't have auto-closed ;)

**Comment by ale7714** [comment]
I created two test reports for app repo and got some discrepancies in coverage percent. Line/file count looks correct. 

`test-reporter`: 
<img width="793" alt="screen shot 2017-03-21 at 10 49 39 pm" src="https://cloud.githubusercontent.com/assets/1709578/24182921/5cf4a08a-0e9b-11e7-869a-f02e9dce4180.png">

Payloads: [Archive.zip](https://github.com/codeclimate/test-reporter/files/860396/Archive.zip)
 
`ruby-test-reporter`:

<img width="758" alt="screen shot 2017-03-21 at 10 49 45 pm" src="https://cloud.githubusercontent.com/assets/1709578/24182911/4d5cb9b4-0e9b-11e7-94ee-5407b9cbd825.png">

To confirm simple cov returns same result as `ruby-test-reporter`
<img width="695" alt="screen shot 2017-03-21 at 8 44 30 pm" src="https://cloud.githubusercontent.com/assets/1709578/24182991/abbcb108-0e9b-11e7-8993-4f439cca38fa.png">

Also here's the resultset for app [resultset.json.zip](https://github.com/codeclimate/test-reporter/files/860401/resultset.json.zip)

**Comment by pbrisbin** [comment]
Could you grab the individual resultset files from a parallel run in CI?

**Comment by ale7714** [comment]
Here are the [individual-resultset.zip](https://github.com/codeclimate/test-reporter/files/861730/sub-resultset.zip) from the CI run

@markbates let me know if you need any more info :)

**Comment by markbates** [comment]
Thanks. That's really useful. I'll be digging into this this afternoon.

**Comment by markbates** [comment]
@ale7714 Can you send me a screenshot of the HTML page that gets generated? Or a CSV that has the following information for both the whole project and a couple of the individual files. I'm trying to figure why my math isn't lining up with theirs. Looking at the Simple Cov source code it should.

Total Lines, Total Lines Covered, Total Lines Missed, Covered Percent

**Comment by ale7714** [comment]
@markbates sure, will send you a zip with the html so you have all the information.

**Comment by ale7714** [comment]
@markbates hope the zip is helpful [coverage.zip](https://github.com/codeclimate/test-reporter/files/862670/coverage.zip).

**Comment by markbates** [comment]
thanks!

**Comment by ale7714** [comment]
After fixes covered percentage is correct.
