### ISSUE TITLE
Support prefix of "./"

### ISSUE THREAD

**Issue by bmulholland** [codeclimate/test-reporter#313]
simplecov-lcov is an lcov formatter for simplecov that includes "./" in its standard path output (https://github.com/fortissimo1997/simplecov-lcov/blob/master/lib/simplecov-lcov.rb#L85).

The commit adding that prefix states it was done to match other formatters: https://github.com/fortissimo1997/simplecov-lcov/commit/bfbbaf8736bdb5caae6e71c98ad2baa8840c49ca.

We didn't have this issue before because the ruby-test-reporter handled the prefix: https://github.com/codeclimate/ruby-test-reporter/blob/master/lib/code_climate/test_reporter/shorten_filename.rb#L10.

Could support for the "./" prefix be added?

**Comment by ale7714** [comment]
@bmulholland 👋, thank for using the `test-reporter` and sorry for the issues you're encountering. I'll try to get you up and running ASAP. 

The `test-reporter` offers the capability to use the flag `--prefix` to be able to trim part of the file path. You can add to the command `format-coverage` or `after-build` the flag `--prefix ./`.  Can you let us know how it goes after trying that?

Also, I'm going to go ahead and close this issue https://github.com/codeclimate/test-reporter/issues/314. It would be more valuable to fix the underlying issue than the workaround. 

Thanks again!

**Comment by bmulholland** [comment]
Using `--prefix "./"` seems to have worked! Or at least, it doesn't generate any errors submitting to CC. How can I verify in CC or my GitHub PR that the coverage is working?

**Comment by ale7714** [comment]
@bmulholland  do you use the [Code Climate browser extension](https://codeclimate.com/browser-extension/)? You should be able to see coverage overlay on your PR or browsing the branch.

**Comment by bmulholland** [comment]
@ale7714 Thank you! I've fully confirmed that the `--prefix` workaround successfully submits test coverage.
