### ISSUE TITLE
Keep getting file not found error trying to run after-build in CircleCI..

### ISSUE THREAD

**Issue by eddieduro** [codeclimate/test-reporter#321]
Generating coverage via jest for a create-react-app.
Inside my config.yml
```
./cc-test-reporter before-build
docker-compose run coverage
docker cp app_coverage_run_1:/app/coverage coverage
./cc-test-reporter after-build --exit-code $? --debug
```
Output:
```
DEBU[0000] about to run format-coverage                 
DEBU[0000] searching for a formatter to use             
DEBU[0000] checking simplecov formatter                 
DEBU[0000] checking search path coverage/.resultset.json for simplecov formatter 
DEBU[0000] checking cobertura formatter                 
DEBU[0000] checking search path cobertura.xml for cobertura formatter 
DEBU[0000] checking search path cobertura.ser for cobertura formatter 
DEBU[0000] checking coverage.py formatter               
DEBU[0000] checking search path coverage.xml for coverage.py formatter 
DEBU[0000] checking excoveralls formatter               
DEBU[0000] checking search path cover/excoveralls.json for excoveralls formatter 
DEBU[0000] checking gcov formatter                      
DEBU[0000] checking search path ./ for GCov formatter   
DEBU[0000] checking gocov formatter                     
DEBU[0000] checking search path c.out for gocov formatter 
DEBU[0000] checking jacoco formatter                    
DEBU[0000] checking search path jacoco.xml for jacoco formatter 
DEBU[0000] checking lcov formatter                      
DEBU[0000] checking search path coverage/lcov.info for lcov formatter 
DEBU[0000] found file coverage/lcov.info for lcov formatter 
DEBU[0000] couldn't load committed at from ENV, trying git... 
INFO[0000] trimming with prefix /root/app/              
DEBU[0000] getting fallback blob_id for source file /app/src/App.js 
ERRO[0000] failed to read file /app/src/App.js
open /app/src/App.js: no such file or directory 
Error: open /app/src/App.js: no such file or directory
```

I have tried specifying prefixes.. attempted going to the lower levels using format / upload everything seems to be throwing an error.. Any ideas?

**Comment by efueger** [comment]
Hi @eddieduro - Happy to help with this.

Do you mind providing a few extra details? You can do that here, or open up a ticket with these at [https://codeclimate.com/help](https://codeclimate.com/help/new).

Please include:
- Repo name
- CI name
- If you use single, parallel or multi-suite builds
- A copy of your CI configuration file
- Any relevant screenshots of your setup

We'll take a look at your configuration as soon as you get that in. Thanks!

**Comment by davehenton** [comment]
Solved via email.

**Comment by friend0** [comment]
You're wasting people's time by not including the resolution inline

**Comment by alastairpayne** [comment]
For those of us without access to those emails; I had a similar problem, here was my fix:

If you're generating your coverage report inside a docker container, then you need to make sure the coverage report is actually available outside that container when you want to send it to code climate. You can do this by copying it out (as in the original comment) or my mounting the coverage folder as a volume. 

Similarly, when formatting the report, it looks like the test-reporter wants to access the files listed in the report, **so you need more than just the report itself**, you will also need the src folder, so copy/mount that as well as the coverage.

Finally, remember to set the --prefix on the formatter, as the documentation says;

> For example, if you're running tests within a docker container and your app code is located at /usr/src/app, you'd use:
> cc-test-reporter format-coverage --prefix /usr/src/app
