### ISSUE TITLE
Question: Guidance on using Lerna repositories, Travis CI, and Node

### ISSUE THREAD

**Issue by awentzel** [codeclimate/test-reporter#324]
I'm having trouble finding documentation on how to configure Code Climate using Travis CI so that is will pick up the code coverage files.  Currently, my Lerna repository has a bunch of `/packages/*`.  My `codeclimate.yml` file is in the root.  Each package is using jest with code coverage turned on and configured.

What's the best way to set this up so code climate can get my coverage files?  I haven't found much documentation on code climate for Node and definitely not any for Lerna repositories.

My repository is https://github.com/Microsoft/fast-dna/

Thanks,

**Comment by awentzel** [comment]
Is it possible to take look at this and provide guidance?  We're blocked until we figure this part out.  Thanks

**Comment by davehenton** [comment]
Hey @awentzel , sorry about the delay in getting to this. Happy to help. Though we don't have any documentation for setting up test reporting with Lerna repos, I'll be happy to take a closer look. Do you mind writing into [support](https://codeclimate.com/help) with the following info:

- Repo name
- CI name
- If you use single, parallel or multi-suite builds
- A copy of your CI configuration file
- Output from your CI when using the --debug flag in your CI configuration
- Any relevant screenshots of your setup

Sorry about the extra work with that! I'll be awaiting your reply to troubleshoot further.

**Comment by awentzel** [comment]
Hi @davehenton, i just noticed your reply.  I will send in the information you requested first thing tomorrow.  Thanks for your help

**Comment by awentzel** [comment]
Ticket submitted.  I may keep this open until I hear back so I can share the solution to my problem with the community.

**Comment by davehenton** [comment]
Closing this one out. We were able to use the following configuration (referenced in [this issue](https://github.com/codeclimate/test-reporter/issues/263#issuecomment-346983961)) to setup test reporting with this Lerna repo. 

```
  # See https://github.com/codeclimate/test-reporter/issues/263
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      for f in packages/*; do
        if [ -d $f ]; then
          echo $f;
          ./cc-test-reporter format-coverage -t lcov -o coverage/coverage.${f//\//-}.json $f/coverage/lcov.info;
        fi
      done;
      ./cc-test-reporter sum-coverage -o coverage/coverage.total.json coverage/coverage.*.json;
      ./cc-test-reporter upload-coverage -i coverage/coverage.total.json;
    fi
```
