### ISSUE TITLE
format-coverage fails on 'failed to read file file.js'

### ISSUE THREAD

**Issue by bushidocodes** [codeclimate/test-reporter#331]
Team Code Climate:

I've recently had some trouble getting my test reports uploaded for a new project.

I'm running the latest version of the reporter:
```bash
circleci@9280b9b5c924:~/repo$ ./cc-test-reporter -v
Code Climate Test Reporter 0.5.1 (988d719a7ec708b7e9d853ab61767e8f0cdc3381 @ 2018-03-19T16:12:36+0000)
```

and this is what I see when I interactively re-run the command in my config:
```bash
circleci@9280b9b5c924:~/repo$ ./cc-test-reporter format-coverage -t lcov coverage/lcov.info -d
DEBU[0000] coverage path coverage/lcov.info
DEBU[0000] using formatter lcov
DEBU[0000] checking search path coverage/lcov.info for lcov formatter
DEBU[0000] couldn't load committed at from ENV, trying git...
INFO[0000] trimming with prefix /home/circleci/repo/
DEBU[0000] getting fallback blob_id for source file file.js
ERRO[0000] failed to read file file.js
open file.js: no such file or directory
Error: open file.js: no such file or directory
```

Here is the command running without a target input or type. It looks like it infers things properly since my LCOV report is in the expected place, but it errors out anyways:

```bash
circleci@9280b9b5c924:~/repo$ ./cc-test-reporter format-coverage -d
DEBU[0000] searching for a formatter to use
DEBU[0000] checking lcov formatter
DEBU[0000] checking search path coverage/lcov.info for lcov formatter
DEBU[0000] found file coverage/lcov.info for lcov formatter
DEBU[0000] couldn't load committed at from ENV, trying git...
INFO[0000] trimming with prefix /home/circleci/repo/
DEBU[0000] getting fallback blob_id for source file file.js
ERRO[0000] failed to read file file.js
open file.js: no such file or directory
Error: open file.js: no such file or directory
```

Thanks for the help!

**Comment by bushidocodes** [comment]
Team Code Climate: it's a friday miracle. Yesterday, I refactored various parts of my build process, and today, I decided to attempt to upload my code coverage reports, and hip-hip-huzzah it worked! I am befuddled as to what the issue was, but I'm sure it was on my end and pleased to see my 85% score reflected on the dash.

**Comment by maxjacobson** [comment]
@bushidocodes Awesome to hear it Sean! Not sure what was going on there, but glad it's resolved now :tada: :taco:
