### ISSUE TITLE
why is it trying to load html files?

### ISSUE THREAD

**Issue by chrisbutler** [codeclimate/test-reporter#333]
I've been banging my head against a wall trying to understand this output from the `cc-test-reporter` binary:

`/bin/cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.cucumber.json $CIRCLE_ARTIFACTS/coverage/cucumber/.resultset.json`

```
/bin/cc-test-reporter: line 1: html: No such file or directory
/bin/cc-test-reporter: line 2: syntax error near unexpected token `<'
'
```

It seems like it's trying to load the `index.html` (also generated from simplecov) file in the `coverage/` directory... not sure how that's possible since the `.resultset.json` file is clearly specified

**Comment by chrisbutler** [comment]
followup, i've ensured that simplecov isn't generating any html and i'm still getting the same errors. this is on circle-ci, cache disabled

**Comment by chrisbutler** [comment]
second followup... attempting to debug and setting `-d` or `--debug` and suddenly there are no errors? what is going on?!?!?

**Comment by chrisbutler** [comment]
seems like you're right about it receiving an html response from the api:

```bash
circleci@95b699b761a7:~$ /bin/cc-test-reporter
/bin/cc-test-reporter: line 1: html: No such file or directory
/bin/cc-test-reporter: line 2: syntax error near unexpected token `<'
'bin/cc-test-reporter: line 2: `<head><title>503 Service Temporarily Unavailable</title></head>
```

**Comment by maxjacobson** [comment]
Aha, great catch.

Re your suggestion: hmm, in that case, what would get written to the file instead of the HTML? I'm concerned it would still write the file, make it executable, and then try to execute it, and you would get another error. Does that make sense?

**Comment by chrisbutler** [comment]
it should just fail to write anything in this case, so the docker build step would fail

**Comment by maxjacobson** [comment]
Ah. We generally recommend people add an `|| true` to these lines, because it can be frustrating for a temporary CC outage to lead to a failing build. If you're comfortable with that (and we certainly will do our best to avoid/minimize outages!) then that sounds like a good approach! I'm going to go ahead and close this now since your sleuthing has gotten to the bottom of it :mag:
