### ISSUE TITLE
Jacoco: no such file or directory on mult src directories

### ISSUE THREAD

**Issue by madppiper** [codeclimate/test-reporter#347]
Hey everyone,

I use ./cc-test-reporter in combination with JaCoCo and an ant script. The project features a module structure and is setup in such a way that JUnit captures during runtime. The following src directories exist: 

./applications/accounting/src
./applications/cms/src
./applications/content/src
./applications/humanres/src
./applications/manufacturing/src
./applications/marketing/src
./applications/order/src
./applications/party/src
./applications/product/src
./applications/securityext/src
./applications/setup/src
./applications/shop/src
./applications/solr/src
./applications/workeffort/src
./framework/base/src
./framework/catalina/src
./framework/common/src
./framework/datafile/src
./framework/entity/src
./framework/entityext/src
./framework/geronimo/src
./framework/minilang/src
./framework/security/src
./framework/service/src
./framework/start/src
./framework/testtools/src
./framework/webapp/src
./framework/webtools/src
./framework/widget/src
./specialpurpose/assetmaint/src

JaCoCo generates a proper report in the end, but cc-test-reporter seems to have a problem with the modular structure and will run into a 'no such file or directory' error on 

` ./cc-test-reporter format-coverage runtime/logs/jacoco-report/xml/report.xml -d -t jacoco`

I tried setting the JACOCO_SOURCE_PATH to include the multiple directories, but it seems as if the script is not capable of handling multiple input directories. Would it be possible to update the script to allow the parsing of multiple src directories like 
`JACOCO_SOURCE_PATH=applications/accounting/src:applications/cms/src:applications/content/src ...` ?

**Comment by ale7714** [comment]
Hi @madppiper, thank you for using the `test-reporter`. We just release a [new version](https://github.com/codeclimate/test-reporter/blob/master/CHANGELOG.md#v062-2018-07-31) of the test-reporter to address this. 

You can set multiple source paths by including them separated by white space. For example, `JACOCO_SOURCE_PATH="app1/main app2/main"`.

Thanks to @atoulme for the [contribution](https://github.com/codeclimate/test-reporter/pull/348).

**Comment by madppiper** [comment]
You guys are fantastic. Thank you so much
