### ISSUE TITLE
Coverage not reporting on non-member pull requests

### ISSUE THREAD

**Issue by kylemh** [codeclimate/test-reporter#364]
Loving the integration so far, but confused as to why [this PR](https://github.com/OperationCode/front-end/pull/136) never has coverage reported.

The .com/repos/${id}/settings/test_reporter URL also doesnt seem to show his PR or test report.

https://github.com/OperationCode/front-end/blob/master/.travis.yml

**Comment by dblandin** [comment]
Hi @kylemh!

Thanks for getting in touch. That's certainly strange and something that we'll have to dig into.

I recommend opening up a support ticket with our customer success team, so we can best get this prioritized: https://codeclimate.com/help/new

Thanks!

**Comment by kylemh** [comment]
Emailed! Thanks.
