### ISSUE TITLE
How can I change the 'coverage' working directory to 'build/coverage'?

### ISSUE THREAD

**Issue by IgorNovozhilov** [codeclimate/test-reporter#368]
I use [nyc](https://www.npmjs.com/package/nyc), with option in `package.json`:
```json
  "nyc": {
    "temp-directory": "./build/nyc_output",
    "report-dir": "./build/coverage"
  }
```

How can I change the 'coverage' working directory to 'build/coverage' for `cc-test-reporter`?
1. If I use:
```sh
./build/.cc-test-reporter after-build --coverage-input-type lcov --exit-code 0
```
That result:
```
Error: could not find any files in search paths for lcov. search paths were: , coverage/lcov.info
```

2.  If I use:
```sh
./build/.cc-test-reporter format-coverage --input-type lcov build/coverage/lcov.info
./build/.cc-test-reporter upload-coverage
```
In that case  `cc-test-reporter` is creating unwanted directory and file: `./coverage/codeclimate.json`. Which in my case should be placed in `./build/coverage/codeclimate.json`

**Comment by IgorNovozhilov** [comment]
Or perhaps there is another way to specify a report file?
Other clouds that implement code coverage analysis determine the location of the report within the catalog automatically. For example: **codecov**.
Or example, in **codacy**, you can send a report to input:
```
codacy-coverage < build/coverage/lcov.info
```

**Comment by ale7714** [comment]
@IgorNovozhilov thank you for writing. The `format-coverage` command allows you to specify the output path by using the `--output` flag. For example,
```
./build/.cc-test-reporter format-coverage --input-type lcov build/coverage/lcov.info --output build/coverage/codeclimate.json
./build/.cc-test-reporter upload-coverage --input build/coverage/codeclimate.json
``` 

Thanks! Let us know if we can help with anything else.

**Comment by IgorNovozhilov** [comment]
@ale7714, thanks, it works.
I think in [documentation](https://docs.codeclimate.com/docs/configuring-test-coverage), it would be nice to add links to the list of all commands with available properties and flags
