### ISSUE TITLE
Need to be able to override previous coverage report

### ISSUE THREAD

**Issue by kojiromike** [codeclimate/test-reporter#380]
We are working with a complex legacy application whose test runner is in a separate repository. When experimenting with some changes to make the tests run faster, the test runner uploaded reports with the commit hash pointed at the head of several unrelated PRs in the main application. Now codeclimate is rejecting those prs because their coverage has apparently dropped, but it hasn’t. We can’t update the real  coverage report because we get the message “A test report for commit [whatever] already exists, skipping upload"

**Comment by wfleming** [comment]
Hi, can you please open a support ticket at https://codeclimate.com/help for this? This case is more related to our internal systems than the rest reporter itself. Our support team can help work on this.

**Comment by kojiromike** [comment]
✅ done

**Comment by wfleming** [comment]
Going to close this issue since it's been filed as a support request and this behavior has more to do with our API than the test reporter.

**Comment by Morozzzko** [comment]
@kojiromike could you please share what you've learned after contacting support?

[Some people](https://stackoverflow.com/questions/45275835/how-to-overwrite-code-climate-test-coverage-report-to-the-same-commit) and I have been facing the same issue lately, and I came here looking for a CLI flag `--force` or something like that. All the googlable pages don't show anything useful, so I'm kinda desperate at this point.

It would be really helpful if there was a link / a quote from support / something like that.

**Comment by kojiromike** [comment]
@Morozzzko unfortunately support pretty much just added my request to an internal backlog for future development consideration. They didn't actually solve my issue.

**Comment by Morozzzko** [comment]
Ah, that's too bad. Thank you for the follow-up! 

I guess it's better for us to still open a support ticket in hope they'll move it up the backlog.
