### ISSUE TITLE
Rails 6 support

### ISSUE THREAD

**Issue by knagode** [codeclimate/test-reporter#388]
```
Bundler could not find compatible versions for gem "simplecov":
  In Gemfile:
    simplecov

    codeclimate-test-reporter was resolved to 1.0.9, which depends on
      simplecov (<= 0.13)
```

I am seing this after upgrading to Rails 6. Should this work with Rails 6 already?

**Comment by wfleming** [comment]
You're using the older https://github.com/codeclimate/ruby-test-reporter, which has a direct dependency on simplecov and is deprecated.

This repository is for the newer language-agnostic codeclimate test reporter. If you switch to this test reporter you can use whatever version of simplecov is appropriate for you.

See https://docs.codeclimate.com/docs/configuring-test-coverage for docs on setting up this test reporter.

**Comment by knagode** [comment]
@wfleming I was a bit confused but now I understand :D thanks!
