### ISSUE TITLE
Ambiguous error message

### ISSUE THREAD

**Issue by tsikerdekis** [codeclimate/test-reporter#393]
My latest build produces a test coverage but I just get under STATE an ambiguous ERROR message.

Clicking on the test report does not show me what the error is, which means I don't know how to fix it:

https://codeclimate.com/repos/5c8d9bc25f36b402b50003cb/settings/test_reports/5ca01accf2b1bb026f0003cc

Here is my travis file:
https://github.com/athina-edu/athina/blob/master/.travis.yml

The weirdest thing is that the report actually contains results about test coverage so I am not sure why there is an error.

**Comment by tsikerdekis** [comment]
Is there any progress on figuring out what this error is? Or if we at least had a log display to see what file is causing it.

**Comment by efueger** [comment]
Hi @tsikerdekis -

Sorry for the delay! On the backend, I see there's an error message with:

> Details: {"error"=>{"class"=>"CC::Wally::Batch::TestFileReportsBatch::InvalidTestFileReport", "message"=>"Invalid path part \"/\"", "file_document"=>"{\"_id\"=>BSON::ObjectId('5cb1042e4376266fb1002f4d'), \"type\"=>\"test_file_reports\", \"blob_id\"=>\"29fc1da45900ece22ff3ebb73a6b7ccf607e6a1a\", \"coverage\"=>\"[1,1,1,1,1,null,null,null,1,null,1,1,0,null,null,1,1,null,1,1,1,1,1,null,1,null,1,1,1,1,null,null,null,null,1,0,0,0,0,0,0,0,null,0,0,null,0,0,null,null,null,1,1,1,1,null,null,null,1,1,null,0,1,1,0,0,0,0,1,1,null,null,null,1,1,1,1,1,1,1,null,1,1,1,1,1,1,1,null,1,1,1,1,0,0,0,0,0,1,1,1]\", \"covered_percent\"=>70.27027027027027, \"covered_strength\"=>0.7027027027027027, \"line_counts\"=>{\"missed\"=>22, \"covered\"=>52, \"total\"=>74}, \"path\"=>\"**/home/travis/virtualenv/python3.7.1/lib/python3.7/distutils/__init__.py**\", \"test_report_id\"=>BSON::ObjectId('5cb1042e86b8411504002b7c')}"}}

Do you need to include that file in your coverage results? I think it's something that's being generated on the fly. Excluding that should help!

Let me know if that gets things rolling. 👌

**Comment by tsikerdekis** [comment]
Thank you @efueger. Indeed excluding the file helped resolve the issue. I actually used --omit *lib* since I have no lib folder in my project.
