### ISSUE TITLE
Error: could not find coverage info for source files

### ISSUE THREAD

**Issue by ceelogre** [codeclimate/test-reporter#394]
I'm trying to set up Code climate for my app and I keep getting this error on CircleCI.
 `package.json` snippet
```{
  "name": "dista",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www",
    "test": "nyc mocha"
  },
```
`config.yml`
```version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: xxx
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run:
          name: Setup CC test reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter

            chmod +x ./cc-test-reporter

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run tests and reporter
          command: |
            # notify CC of pending test report using before-build and upload to CC
            ./cc-test-reporter before-build
            npm test
            ./cc-test-reporter after-build -t lcov -d --exit-code $?
```
Note when I run `npm test` in my terminal, I can see the `coverage` directory being created.
For further details, the repo is  #[here](https://github.com/ceelogre/localAware)

**Comment by wfleming** [comment]
Hi @ceelogre,

I believe you're hitting an edge-case where the test reporter doesn't see an empty file as a valid coverage file and ignores it. It looks like your `lcov.info` file is empty since your test suite isn't really testing anything right now. The error in this case is certainly a bit confusing, sorry.

If you start writing real tests & get your test suite configured so the `lcov.info` file has contents I suspect it will start working.

**Comment by ceelogre** [comment]
Thanks, I'll go ahead and add a few tests and see if it works then close the issue.

**Comment by ceelogre** [comment]
I have added more tests but the error persists.

**Comment by wfleming** [comment]
Hi @ceelogre,

Looking at your latest [master build on circle](https://circleci.com/gh/ceelogre/localAware/44), it looks like `npm test` is hanging and causing the build to time out. That also happened when I cloned the repo locally and ran the tests. 

Are you seeing the tests complete successfully locally for you? If so, can you share the contents of the `lcov.info` file here and the error message from the test reporter?

**Comment by ceelogre** [comment]
Thanks, @wfleming,
I realized that this was the issue though I haven't fixed it. I'm working on it and will share the results in a while.

**Comment by ceelogre** [comment]
I've fixed Mocha hanging problem but `lcov.info` is still empty.

**Comment by ceelogre** [comment]
Fixed it. Hadn't passed `lcov` to `nyc` when running the tests.
