### ISSUE TITLE
Fetching the test reporter and calling `before-build` all of a sudden failing

### ISSUE THREAD

**Issue by toymachiner62** [codeclimate/test-reporter#396]
I have a dockerfile (actually over 100) with these lines

```dockerfile
# Fetch code climate binary
RUN curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
RUN chmod +x ./cc-test-reporter

# Notify code climate a build is starting
RUN ./cc-test-reporter before-build
RUN npm run lint && npm run test-coverage
```

I'm all of a sudden getting this error when trying to deploy my app.

```
Step 18/35 : RUN ./cc-test-reporter before-build
---> Running in 7c747687630e
./cc-test-reporter: line 1: can't open html: no such file
./cc-test-reporter: line 2: syntax error: unexpected redirection
The command '/bin/sh -c ./cc-test-reporter before-build' returned a non-zero code: 2
make: *** [build] Error 2
```

Is there a known issue at the moment with fetching the cc-test-reporter?
This has literally worked like 1K times in the last 4 days (and thousands of times on multiple repo's in the past 6 months)

**Comment by efueger** [comment]
Thanks, Tom! We discussed in a different thread. Making a note here in case someone hits this in the future.

There that there was a latency alert for our test reporter late yesterday afternoon. We adjusted settings to give that more buffer. 👌
