### ISSUE TITLE
Configure coverage using codeclimate.yml

### ISSUE THREAD

**Issue by rhwood** [codeclimate/test-reporter#401]
Is it possible to configure test coverage (diff percentage, minimum coverage percentage) using .codeclimate.yml?

If so, can you provide an example?

**Comment by danielenricocahall** [comment]
Any status on this?

**Comment by efueger** [comment]
Hi @rhwood and @danielenricocahall - apologies, this slipped through the cracks.

- The .codeclimate.yml only handles analysis configuration. 
- The PR statuses for coverage are handled exclusively in the UI. 

That said, I can definitely see how it'd be useful to have that centralized in one location. 👍

I'll make a note to discuss this with the team. Thanks for the suggestion.

Cheers,
Emily
