### ISSUE TITLE
400 error attempting to submit test coverage

### ISSUE THREAD

**Issue by ksmithut** [codeclimate/test-reporter#407]
The command I'm running after generating test coverage reports for a node project is:

```
./cc-test-reporter after-build --exit-code $?
```

where `$?` evaluates to `0`. Then I get this output:

```
Error: response from https://api.codeclimate.com/v1/repos/[redacted]/test_reports/[redacted]/test_file_reports/batch.
HTTP 400: Invalid query params
Usage:
  cc-test-reporter after-build [flags]

Flags:
  -s, --batch-size int               batch size for source files (default 500)
  -e, --coverage-endpoint string     endpoint to upload coverage information to (default "https://api.codeclimate.com/v1/test_reports")
  -t, --coverage-input-type string   type of input source to use [clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, simplecov, xccov]
      --exit-code int                exit code of the test run
  -r, --id string                    reporter identifier (default "[redacted]")
      --insecure                     send coverage insecurely (without HTTPS)
  -p, --prefix string                the root directory where the coverage analysis was performed (default "[redacted]")

Global Flags:
  -d, --debug   run in debug mode

Exited with code 255
```

The CC_TEST_REPORTER_ID environment variable is set (I redacted it from the above output) and only started breaking today. It was working just fine yesterday, but this only started happening after a refactor of some things to the code base the tests are being run on, so I'm fully willing to admit that I goofed something. Any ideas to point me in the right direction?

**Comment by JustH** [comment]
was coming to submit the same issue. running with same command

**Comment by ale7714** [comment]
👋 @ksmithut, thank you for reaching out! Is the problem happening right now? we introduced a bug at 1:20pm and rollback at 1:30pm. Retrying the build on your CI should fix the issue.

**Comment by ale7714** [comment]
Actually I was able to reproduce the issue. We're looking into it.

**Comment by sourabhguptavc** [comment]
@ale7714 I also experiencing the same issue.

**Comment by akamuraasai** [comment]
What I have noticed is that this 400 error happens when you don't pass a ID explicit into the command. But when you pass a explicit ID, even a correct on, a 401 error occours.

**Comment by ksmithut** [comment]
I rebuilt and it seems to be working now :)

**Comment by mohitDeshpande** [comment]
Started experiencing this issue across the org as of this afternoon. 
Pulling the binary from 
`curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64`

**Comment by ale7714** [comment]
Hi all, we just rolled back a change in our API that cause this issue. I apologize for the inconvenience. Can you please retry your CI build? It should work as expected now. Thank you for your patience. Don't hesitate to reach out if anything.

**Comment by sourabhguptavc** [comment]
I can confirm build is working fine now
