### ISSUE TITLE
Strange error on bitbucket pipelines...

### ISSUE THREAD

**Issue by cetanu** [codeclimate/test-reporter#408]
Howdy,

I've just tried setting up code-climate for my repo and...

I'm running it like this:

```
wget https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o cc-test-reporter
chmod +x cc-test-reporter
./cc-test-reporter before-build
```

Which ends up with the following result:

```
+ ./cc-test-reporter -d before-build
./cc-test-reporter: line 1: --2019-10-10: command not found
./cc-test-reporter: line 2: syntax error near unexpected token `('
./cc-test-reporter: line 2: `Resolving codeclimate.com (codeclimate.com)... 34.193.70.63, 52.6.234.107, 52.7.253.187'
```

I don't understand what's going on here but it looks borked.

This is running inside a `python:3.7` docker image

**Comment by cetanu** [comment]
Actually.....

This is totally my fault for using `wget`

How funny 😄

**Comment by kanav-linktree** [comment]
What did you end up using? I tried yum it doesn't work for me on the amazonlinux base image.

**Comment by cetanu** [comment]
I'm not using code climate anymore, I just use output from `pytest-cov` instead
