### ISSUE TITLE
Checksum binaries

### ISSUE THREAD

**Issue by fede-moya** [codeclimate/test-reporter#456]
It would be nice to have a way to confirm that the downloaded binaries are valid, instead of just running them.

**Comment by BasicBeluga** [comment]
+1 on this. It'd be nice to have these checksums to help mitigate risk of a man-in-the-middle attack.

**Comment by filipesperandio** [comment]
Agreed. Nice to have, difficult to add that to our roadmap =\

**Comment by moyass** [comment]
For a tool that runs in CircleCI, it is essential to have a checksum and/or a signed binary to validate integrity and authenticity.

**Comment by richgerrard** [comment]
@filipesperandio: Considering the codecov supply chain attack, you would be VERY wise to incorporate this in your plan, asap, lest people abandon your tool for the same security risks that codecov exposed everyone to.

**Comment by vbersier** [comment]
I think this is really important

**Comment by fede-moya** [comment]
Folks you can now verify the integrity of your downloads. See [verifying-binaries](https://github.com/codeclimate/test-reporter#verifying-binaries ) for further details.

**Comment by fede-moya** [comment]
Folks you can now verify the integrity of your downloads. See [verifying-binaries](https://github.com/codeclimate/test-reporter#verifying-binaries ) for further details.
