### ISSUE TITLE
Test coverage not showing in the Overview tab

### ISSUE THREAD

**Issue by marcushwz** [codeclimate/test-reporter#491]
First of all, thank you so much for providing a free tier for startup.

I have looked into this [issue](https://github.com/codeclimate/test-reporter/issues/412) but still can't figure my way out.

## Problem
- Test coverage are not showing up in the overview tab even though the report is uploaded.
<img width="629" alt="image" src="https://user-images.githubusercontent.com/40255418/159160227-a6a01ddf-2dfd-49d1-8549-f752f3b80abe.png">

- The integration with GitHub is working properly
<img width="854" alt="image" src="https://user-images.githubusercontent.com/40255418/159160258-9c6749cf-fd05-441f-8f55-9d37f2cad3ff.png">

- And the report uploaded should have the correct BRANCH name
<img width="805" alt="image" src="https://user-images.githubusercontent.com/40255418/159160311-d122a2cb-712f-4550-8eb5-f34e9fd3b214.png">

Appreciate it if anyone can give me some guides on making it work or something that I should be aware of. Thank you.

**Comment by efueger** [comment]
Hi @marcushwz,

Thanks for reaching out! The UI currently only shows coverage for your default branch. 
- Can you try adding a commit to your default branch?

That should do the trick 👌🏼 

Let us know if you bump into anything else! Here to help.

Best,
Emily
