### ISSUE TITLE
Reporter ID Unused

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/test-reporter#51]
```
% env | grep CC
CC_TEST_REPORTER_ID=c4881e09870b0fac1291c93339b36ffe36210a2645c1ad25e52d8fda3943fb4d
% cc-test-reporter upload-coverage                                                                                                                                        ruby-test-reporter:master
Error: response from https://codeclimate.com/test_reports was 401: Repo not found.
Usage:
  cc-test-reporter upload-coverage [flags]

Flags:
  -e, --endpoint string   endpoint to upload coverage information to (default "https://codeclimate.com/test_reports")
  -r, --id string         reporter identifier (default "c4881e09870b0fac1291c93339b36ffe36210a2645c1ad25e52d8fda3943fb4d")
  -i, --input string      input path (default "coverage/codeclimate.json")
```

I tried to verify on the server logs, but ran into some trouble. Maybe you can identify the bug without me figuring out exactly what made it to the server?

My suspicion is that you're reading the reporter-id at _format_ time, but not injecting it if it's only present at _upload_ time. To clarify, these should work:

```
CC_TEST_REPORTER_ID= cc-test-reporter format-coverage
CC_TEST_REPORTER_ID=abc123... cc-test-reporter upload-coverage
```

```
export CC_TEST_REPORTER_ID=
cc-test-reporter format-coverage
cc-test-reporter upload-coverage --id abc123...
```

**Comment by markbates** [comment]
Digging into this, it looks like it isn't being used anywhere in the code. I found the docs that say it's required, https://github.com/codeclimate/test-reporter/blob/master/man%2Fcc-test-reporter-upload-coverage.1.md#-r---id-id, but I haven't been able to find any docs about what to actually do with that value. 

Is it a header? A query arg?

**Comment by pbrisbin** [comment]
Right now, without any server-side changes, it's an attribute in the Payload (`repo_token`). This isn't in the man-pages because user's don't care, but it's in the `DEVELOPERS.md` reference payload.

I realize this sucks, but to make this work without server-side changes, you'd have to do something like:

- `format-coverage` makes a payload without `repo_token`
- `upload-coverage` parses the JSON, adds `repo_token`, then uploads the JSON

Does that make sense?

In the future, I believe the server should accept it as a header to avoid this situation client-side, but we really want to avoid making server-side changes as part of this project.

**Comment by markbates** [comment]
Ok, I'll figure something out.

**Comment by pbrisbin** [comment]
LGTM.
