### ISSUE TITLE
cc-test-reporter throws `html: No such file or directory`

### ISSUE THREAD

**Issue by koic** [codeclimate/test-reporter#520]
I'm not sure of the cause, but I have started to encounter the following error with cc-test-reporter. Since I haven't updated any client libraries, it's likely that something has happened on the server side.

```console
#!/bin/bash -eo pipefail
./tmp/cc-test-reporter before-build
COVERAGE=true bundle exec rake spec
./tmp/cc-test-reporter format-coverage --output tmp/codeclimate.$CIRCLE_JOB.json

./tmp/cc-test-reporter: line 1: html: No such file or directory
./tmp/cc-test-reporter: line 2: syntax error near unexpected token `<'
'/tmp/cc-test-reporter: line 2: `<head><title>504 Gateway Time-out</title></head>

Exited with code exit status 2
```

https://app.circleci.com/pipelines/github/rubocop/rubocop/11062/workflows/baf07982-a94c-4cc9-98f2-efd26a605f73/jobs/310171

**Comment by f-moya** [comment]
Hi @koic!.  I'm Fede from CC . Are you constantly experiencing this ? or is something intermittent ?

**Comment by koic** [comment]
@fede-moya Thank you for the prompt response. Encountered for the first time in https://github.com/rubocop/rubocop/pull/12853. I have not yet reviewed the situation since then.

**Comment by koic** [comment]
@fede-moya It appears that the cc-test-reporter has recovered in the CI following the merge of the above PR:
https://app.circleci.com/pipelines/github/rubocop/rubocop/11063/workflows/2277e517-4e23-46d3-a18a-d2a86aa9c03a/jobs/310195

It may have been a temporary encounter with "504 Gateway Time-out" issue. For now, I will close this issue. I will reopen it if the problem recurs. Thank you for taking your time.
