### ISSUE TITLE
reporter_version includes trailing new-line

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/test-reporter#53]
```
"reporter_version": "0.1.0-rc (cf12ed46a4b10f9a1052b6fa6a22ff8a1e2c1dce @ 2017-03-20T17:19:02+0000)\n"
```

**Ideally**, this would be:

```
"reporter_version": "0.1.0-rc"
```

I would also accept the following variations, ranging from _nicest to me_ to _least difficult to you_:

```
"reporter_version": "0.1.0-rc (cf12ed4)"

"reporter_version": "0.1.0-rc (cf12ed46a4b10f9a1052b6fa6a22ff8a1e2c1dce)"

"reporter_version": "0.1.0-rc (cf12ed46a4b10f9a1052b6fa6a22ff8a1e2c1dce @ 2017-03-20T17:19:02+0000)"
```

**Comment by markbates** [comment]
Ok, so you don't want the SHA or the build timestamp?

**Comment by pbrisbin** [comment]
Ideally no. It's a trade-off with effort, I assume, so I tried to make the requirement a little lax in case for some reason it's _wildly_ more effort to exclude that information.

**Comment by markbates** [comment]
No, it's really easy to do just the `Version`, I just wanted to confirm.

**Comment by pbrisbin** [comment]
LGTM!
