### ISSUE TITLE
Report formatter repo-token

### ISSUE THREAD

**Issue by ale7714** [codeclimate/test-reporter#55]
Currently `RepoToken` is being set by looking for the env var [CC_REPO_TOKEN or REPO_TOKEN](https://github.com/codeclimate/test-reporter/blob/ee3f6b29edd4864c88541093c0b954c331adf4ee/env/env.go#L49). And when uploading coverage  [CC_TEST_REPORTER_ID](https://github.com/codeclimate/test-reporter/blob/87b79108dbf28c770a56f0a0fa5f2d85ae6fba37/cmd/upload-coverage.go#L75) is required.

When CC_REPO_TOKEN is not set causes the report to have empty `repo_token`, which means currently we need to set CC_REPO_TOKEN and CC_TEST_REPORTER_ID. The desired behavior would be to only be required to give CC_TEST_REPORTER_ID.

**Comment by pbrisbin** [comment]
I _think_ this is addressed. @markbates please assign to @ale7714 to confirm, if so.

**Comment by ale7714** [comment]
I confirmed is working as expected. Closing the issue :)
