### ISSUE TITLE
after-build command

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/test-reporter#60]
*TODO*: man-page.

This will be equivalent to the expected use of `format-coverage`/`sum-coverage` then `upload-coverage`. It should accept options and read env vars that would or could be used by the sub-commands it represents.

Additionally it should take an `--exit-code` option, so we know if the build (tests) we're reporting after were successful or not. We need to confirm what env vars hold this exit code in the `post` steps of the various CI systems. Perhaps we should get it via env inference instead of an option?

## Options

*Just capturing some rough thoughts for now, will formalize before work begins*

- `--coverage-endpoint x` behaves like `upload-coverage --endpoint x`
- `--coverage-output x` behaves like `format-coverage --output x; upload-coverage --input x` (TODO: consider `sum-coverage` here)
- `--reporter-id` is passed along as-is to `upload-coverage`

**Comment by pbrisbin** [comment]
On second though, this command should probably not get into `sum-coverage` territory, we should keep that use-case requiring low-level commands directly for now.

**Comment by markbates** [comment]
Where should the value of `--exit-code` be stored/sent?

**Comment by markbates** [comment]
Here are the current options for the `format-coverage` and `upload-coverage` commands.

Current options for the `format-coverage` command:

```
  -t, --input-type string   type of input source to use [simplecov, lcov]
  -o, --output string       output path (default "coverage/codeclimate.json")
  -p, --prefix string       the root directory where the coverage analysis was performed
```

Current options for the `upload-coverage` command: 

```
  -s, --batch-size int    batch size for source files (default 500)
  -e, --endpoint string   endpoint to upload coverage information to (default "https://api.codeclimate.com/v1/test_reports")
  -r, --id string         reporter identifier
  -i, --input string      input path (default "coverage/codeclimate.json")
```

Here are my proposed options for the `after-build` command.

```
  -t, --input-type string   type of input source to use [simplecov, lcov]
  -p, --prefix string       the root directory where the coverage analysis was performed
  -s, --batch-size int    batch size for source files (default 500)
  -e, --endpoint string   endpoint to upload coverage information to (default "https://api.codeclimate.com/v1/test_reports")
  -r, --id string         reporter identifier
```

A few of the options can be set automatically since we're running them together. For example, we can save the output of the `format-coverage` command wherever we want and pass that directly on to the `upload-coverage` command since they'll be done in one step.

@noahd1 @pbrisbin @ale7714 thoughts?

**Comment by pbrisbin** [comment]
Those combined options (and omissions) look right to me. However, when they're flags on `after-build` they should get some additional qualification that's not needed when they're flags to a specific sub-command. 

For example, since `upload-coverage` is already a *coverage-specific* sub-command, it can use an option like `--endpoint` itself, which makes sense in that context. Since `after-build` will some day do more than just coverage, it should take `--coverage-endpoint`. Same for `--input-type`/`--coverage-input-type`.

`--id` and `--prefix` can stay as-is because they do apply to all `after-build` activities.

I'm less confident in what do do about `--batch-size`, but I'd suggest `--upload-batch-size`. Again, `upload-coverage --batch-size` makes sense in that context, but in the general world of `after-build` operations, it should be a bit more qualified. My assumption is that if/when we add another `upload-foo` operation (with its own `--batch-size` option), it's unlikely we'd want *different* batch sizes across them (hence not using `--coverage-batch-size` or `--coverage-upload-batch-size`).

For `--exit-code`: this would be used to determine behavior. *Today* this means don't upload coverage if the tests failed (exit-code != 0). *In the future*, we might want to report that fact to the server, so we can show you CI pass/fail rate, etc.

Hopefully that all made sense?

**Comment by markbates** [comment]
Yep! That all made sense. Thanks.

**Comment by ale7714** [comment]
Confirmed is working :)
