### ISSUE TITLE
lcov support

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/test-reporter#61]
`format-coverage` should locate `lcov.info` and process it into `coverage/codeclimate.json` correctly.

The README.me for [instanbul](https://github.com/gotwarlost/istanbul#getting-started) states:

> and this should produce a coverage.json, lcov.info and lcov-report/*html under ./coverage

Because of the missing oxford, I'm not sure if this means `./lcov.info` or `./coverage/lcov.info` is produced by default.

Perhaps we should look for both? If it's easy enough, we should list out default paths for other popular lcov-compatible JS tools as well and check them all.

**Comment by ale7714** [comment]
@markbates i've been testing lcov support in one of our repos. Total coverage and line counts looks fine. But coverage for al source file is 0. I attached the lcov file and the payload 
[coverage.zip](https://github.com/codeclimate/test-reporter/files/900439/coverage.zip)

**Comment by markbates** [comment]
@ale7714 just pushed up a fix in #93

**Comment by ale7714** [comment]
Tried again and looks fine
