### ISSUE TITLE
Input type flag (-t, --input-type) to format-coverage

### ISSUE THREAD

**Issue by noahd1** [codeclimate/test-reporter#70]
`format-coverage` should take an optional `-f` flag which will accept `simplecov`, and soon `lcov`.

If an unsupported format is passed, `format-coverage` should report that the format is not supported.

Each format will infer coverage file location(s). If the files aren't found in those locations, an error should be printed that notes that no coverage files could be found, and the search paths we used.

If no `-f` flag is passed, we will attempt to use formats in an order we specify (`simplecov` then `lcov` then ...). Each format will infer file locations to look for coverage files for now (eventually we may want to support a `-i` for file location instead of inferring). If no files are found for any formatter, we should report that the reporter could not find any applicable test coverage files.

We also need to update any applicable man pages to reflect this option.

/c @pbrisbin @GordonDiggs for review

**Comment by pbrisbin** [comment]
I'm curious what's motivating this. Maybe re-writing in our preferred Feature format would clarify?

I'm slightly uneasy about having a `--format` option to a `format-coverage` command where the "format" option isn't for indicating something about the _output_. Maybe this is my own confusion and it could be viewed either way. As alternatives, I'd suggest:

- `-t`, `--input-type`
- `-s`, `--source`

**Comment by GordonDiggs** [comment]
The motivation here is projects that have, for example, both Ruby and JavaScript coverage files. Currently, only the Simplecov files would be picked up (because we use the first we find and then exit). This lets them run `format-coverage` multiple times to pick up both sets of coverage data

**Comment by GordonDiggs** [comment]
I'd be ok with `-t` being the flag

**Comment by pbrisbin** [comment]
Cool works for me. I'm slightly partial to `--source simplcov` because that's the language I'm using in the man-pages, but I don't feel strongly.

**Comment by noahd1** [comment]
I think source is too overloaded a term to consider in this context, but I like -t

**Comment by ale7714** [comment]
@markbates I just tried running `format-coverage` with the -t flag and got 
```console
./cc-test-reporter format-coverage -t 'lcov'
Error: open : no such file or directory
Usage:
  cc-test-reporter format-coverage [flags]

Flags:
  -t, --input-type string   type of input source to use [simplecov, lcov]
  -o, --output string       output path (default "coverage/codeclimate.json")
  -p, --print               prints to standard out only
```

If I ran format-coverage without the -t flag, it finds the `lcov` file and formats it correctly.

**Comment by ale7714** [comment]
Small update running `/cc-test-reporter format-coverage -t simplecov` in our ruby repo. It does format successfully.

**Comment by markbates** [comment]
@ale7714 @noahd1 can this be closed?
