### ISSUE TITLE
Debug flag 

### ISSUE THREAD

**Issue by ale7714** [codeclimate/test-reporter#73]
`test-reporter` will accept an optional flag [`-d, --debug`](https://github.com/codeclimate/test-reporter/blob/1be9d22a61d05cf3c4b6d3306bc28d271f3a430d/man/cc-test-reporter.1.md#-d---debug) that will output debug messages during the execution of a command.

**Comment by ale7714** [comment]
@markbates i tried this flag for `format-coverage`/`sum-coverage` and it's not available yet. Assigning back to you.

**Comment by markbates** [comment]
@ale7714 Currently this is only implemented on the `upload-coverage` command. What would you like it to do for the other commands?

**Comment by ale7714** [comment]
@markbates i only notice this because the error i'm getting when running `cc-test-reporter format-coverage -t lcov`. I think it will be helpful to see the paths that's trying to check if we pass a debug flag.

**Comment by ale7714** [comment]
Closing. It's working as expected now.
