### ISSUE TITLE
-p, --prefix for format-coverage

### ISSUE THREAD

**Issue by ale7714** [codeclimate/test-reporter#74]
`format-coverage` should take an optional `-p, --prefix` that represents the root directory where the coverage analysis was performed. 

When `-p` flag is passed, the `test-reporter` will trim from the source file name the prefix given on the flag instead of the working directory. 

When no `-p`  flag is passed, will continue to perform current behavior which is trimming from file name the working directory.

TODO: update man pages and parallel test usage 

cc @pbrisbin for review  
@noahd1 the motivation of this issue is that the user is able to run all the `test-reporter` commands after all the tests are executed.

**Comment by pbrisbin** [comment]
One question I have is if `--prefix` should affect the `environment.pwd` value sent in the payload. We don't use this server-side AFAICT, but I'm not sure what'd be Right.

If it _should_, and we _also_ eventually split the responsibilities such that `format-coverage` only adds coverage-related values and the metadata is added by `upload-coverage`, then it too will need to accept `--prefix`.

**Comment by ale7714** [comment]
@pbrisbin good point, i think it should or at least save it as one more attribute in `environment`.

**Comment by noahd1** [comment]
I can see there being an `environment.pwd` and `options.prefix` where the `options` namespace represents the set of options the user specified. But the working directory is just the working directory.

**Comment by ale7714** [comment]
Tried it locally, looks fine :)
