### ISSUE TITLE
Support for Clover XML input

### ISSUE THREAD

**Issue by brynary** [codeclimate/test-reporter#78]
We should support the [Clover](https://www.atlassian.com/software/clover) XML coverage format as input. This appears to be [the XSD](https://gist.github.com/aik099/8556655).

Here's an example of how PHP tooling [generates Clover-compatible XML](https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/Report/Clover.php). And here's [an example](https://phpunit.de/manual/current/en/logging.html#logging.codecoverage.xml)

**Comment by dblandin** [comment]
Ditto on this issue. Looks like support was added in https://github.com/codeclimate/test-reporter/pull/115

@noahd1 @ale7714 Still needs acceptance or ready to close?

**Comment by ale7714** [comment]
yep, ready to close i think :)
