### ISSUE TITLE
Support for JaCoCo XML input

### ISSUE THREAD

**Issue by brynary** [codeclimate/test-reporter#79]
[JaCoCo](http://www.eclemma.org/jacoco/) ([source code](https://github.com/jacoco/jacoco)) is a free Java coverage tool.

It can output XML, which we should support. [Here's the DTD.](http://www.eclemma.org/jacoco/trunk/coverage/report.dtd) And here are [some examples](https://github.com/search?utf8=%E2%9C%93&q=filename%3Ajacoco+extension%3Axml&type=Code).

**Comment by GordonDiggs** [comment]
@markbates I also added an example to the DEVELOPERS.md file. There is an XML format that we can support if the DTD is difficult
