### ISSUE TITLE
gzip request body 

### ISSUE THREAD

**Issue by ale7714** [codeclimate/test-reporter#82]
Ability to compress request body with gzip. 

Also an optional flag `--no-compression` can be passed so compression is skipped. 

HTTP headers should be set appropriately based on whether compression was used or not used.

cc @pbrisbin @noahd1

**Comment by pbrisbin** [comment]
@noahd1 not sure who should do what when, but just wanted to flag: man-page update :)

**Comment by ale7714** [comment]
I'm closing this issue for now since it's not a priority for this milestone anymore. We can reopen it when we revisit this subject again.
