### ISSUE TITLE
Publish target should be safer

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/test-reporter#88]
Currently, `make publish` will overwrite anything existing already in the S3 bucket. This is preferred for the floating `-head` and `-latest` binaries, but we should try to avoid accidentally overwriting any immutable `-$(VERSION)` binaries.

We haven't done this yet because:

- It would require individual `cp` operations and (we believe) duplicating the list of architectures
- `aws s3 cp` doesn't support the usual `cp` flags `--no-clobber`, and `--force` to control what happens when the target exists; we might have to implement it ourselves by checking `aws s3 ls`

**Comment by ale7714** [comment]
Possibly implementation to avoid overriding an existing release: 

```
publish: VERSION_COUNT=$(shell $(AWS) s3 ls s3://codeclimate/test-reporter/test-reporter-$(VERSION) | wc -l)
publish:
	if [ $(VERSION_COUNT) -gt 0 ]; then \
		echo "Version already published, skipping publish..."; \
	else \
		$(AWS) s3 cp --acl public-read --recursive artifacts/bin/ s3://codeclimate/test-reporter/ --exclude "*" --include "test-reporter-$(VERSION)*" --include "test-reporter-latest*"; \
	fi;
```

**Comment by dblandin** [comment]
Closing with #135.
