### ISSUE TITLE
sum-coverage --parts flag

### ISSUE THREAD

**Issue by ale7714** [codeclimate/test-reporter#90]
`sum-coverage` should require a `-p, --parts <total-number>`  flag where `total-number` represents the amount of partial payload this command have to sum.  

When flag is passed, it counts the partial payloads and if it's less than specified, it exits with an error `Missing parts: expected total-number, found number`.

TODO: update man pages and parallel test usage

cc @pbrisbin

**Comment by pbrisbin** [comment]
WDTY of the simpler `-p`, `--parts N`? I'm not sure "require" is adding any value here, you're saying how many parts you intend to sum, and it will error if a different number is actually found.

**Comment by ale7714** [comment]
Working as expected :)
