### ISSUE TITLE
Support test coverage reporting without git or a git repository present

### ISSUE THREAD

**Issue by dblandin** [codeclimate/test-reporter#94]
## Context

Among our four existing official test reporters for [ruby](https://github.com/codeclimate/ruby-test-reporter), [python](https://github.com/codeclimate/python-test-reporter), [javascript](https://github.com/codeclimate/javascript-test-reporter), and [php](https://github.com/codeclimate/php-test-reporter), there is inconsistent support for submitting test coverage reports without git and a git repository present. While we've worked with community contributors to add partial support. this has not been prioritized internally as a general test reporter feature.

There is also inconsistent support from CI providers for commit information within the CI environment. We currently check both the environment and git for information required to generate a coverage report payload.

If the CI provider checks out the source code into a detached HEAD, we can't rely on its `branch`, so we also look for it in the environment via our CI mappings. Conversely, if we can't determine the git branch from the CI environment, we have to rely on git for that information.

Generating file blob IDs for source files included within the test coverage report in order to compare test coverage data with source listings is particularly more reliable when done from git. There are ways of generating file blob IDs from the file content (and most of our existing test reporters include such a fallback) but we've found such solutions to be occasionally incompatible with git's internal methods.

## Related Issues & PRs

https://github.com/codeclimate/ruby-test-reporter/issues/183
https://github.com/codeclimate/ruby-test-reporter/pull/177
https://github.com/codeclimate/ruby-test-reporter/issues/171
https://github.com/codeclimate/ruby-test-reporter/pull/168
https://github.com/codeclimate/ruby-test-reporter/issues/156
https://github.com/codeclimate/ruby-test-reporter/pull/116
https://github.com/codeclimate/ruby-test-reporter/issues/115
https://github.com/codeclimate/ruby-test-reporter/pull/89
https://github.com/codeclimate/ruby-test-reporter/pull/57
https://github.com/codeclimate/ruby-test-reporter/issues/56
https://github.com/codeclimate/ruby-test-reporter/issues/38
https://github.com/codeclimate/javascript-test-reporter/issues/44

## Next Steps

We should determine whether or not to support test coverage reporting without git and a git repository present. I'm personally not 100% clear of what happens when the file blob IDs mismatch. I assume we simply don't render file coverage or file coverage annotations for that file on codeclimate.com. Do we know how often these mismatches take place?

I'll hold back any thoughts on implementation until we've addressed these basic "should we" questions.

**Comment by ale7714** [comment]
You're right, if the blob IDs don't match we don't render the coverage for a source file. Currently we don't have any metric for blob IDs mismatches. 

We use git to get the blob id for constants on builder. Wouldn't this discussion require taking in consideration builder? To have consistent blob ids everywhere?

**Comment by GordonDiggs** [comment]
Possibility here: use libgit2. @markbates talk to @pbrisbin before starting on this for better definition

**Comment by pbrisbin** [comment]
It looks like work already started in https://github.com/codeclimate/test-reporter/pull/102. I think this is the right approach based on all the various caveats, so closing this probably means just getting that over the line.

**Comment by ale7714** [comment]
@markbates i updated the #102 PR to fix specs. The PR got really big because of the `dep` update I mentioned the other day. Feel free to update the PR if you need to.

This PR also addresses the fallback blob id issue https://github.com/codeclimate/test-reporter/issues/99. Gets the blob from the file content by using a function from the go git library.

cc @GordonDiggs @pbrisbin

**Comment by markbates** [comment]
@ale7714 i just merged in #102 does that resolve this ticket as well?

**Comment by ale7714** [comment]
yes! it does :)
