### ISSUE TITLE
Update upload-coverage to use API endpoints 

### ISSUE THREAD

**Issue by ale7714** [codeclimate/test-reporter#97]
upload-coverage command will use API endpoints to create a test reports and its associated test file reports. Following the workflow bellow: 

1. Create a test report using `/test_reports` endpoint [(reference)](https://docs.codeclimate.com/v1.0/docs/api#section-post-test_reports). If successful the endpoint will return the resource with the link to create the test_file_reports:
  ```json
{
  "data": {
    "type": "test_reports",
    "attributes": {
    	"id": "ObjectId",
       ...
   },
  "links": {
    "post_batch": "https://api.codeclimate.com/v1/repos/:repo_id/test_reports/:id/test_file_reports/batch"
   }
}
```

2. Create test file reports by sending batches of 500 source files to the post_batch link from the previous response. Including on the request payload a meta field with current and total batch count. The request must be successful to be able to post the following batch. If a request fails, the test reporter exits the upload coverage with an error message. Reference for this endpoint [here](https://docs.codeclimate.com/v1.0/docs/api#section-post-reposrepo_idtest_reportsidtest_file_reportsbatch).

@pbrisbin @noahd1 @GordonDiggs for review

**Comment by ale7714** [comment]
@markbates from time to time i get this error from the `test-reporter`: 
```console
Post https://cce-dev-big.codeclimate.net/api/v1/repos/58d551b9553b430267000005/test_reports/58f13db6a5d923028428ecb1/test_file_reports/batch: dial tcp: lookup cce-dev-big.codeclimate.net on 10.137.0.1:53: no such host
```
I've been doing load testing and that's why i noticed it.

**Comment by markbates** [comment]
Is that host available? If it can't teach the host, that's a correct error. I haven't seen that URL before, so I assume you plugged that in. My guess is that the server you're hitting during load testing is failing under the load. Apart from showing the error, not sure what you want the tool to do.

**Comment by ale7714** [comment]
@markbates yeah i pass the endpoint with the flag. I will close this issue for now since `upload-coverage` is working as expeced.
