### ISSUE TITLE
Include executable in release

### ISSUE THREAD

**Issue by franklinyu** [codeclimate/test-reporter#98]
Currently we can't just

```shell
curl -L https://tools.codeclimate.com/test-reporter/test-reporter-latest
```

I guess that's because

> this is *proposed* usage, we've not built this yet.

It would, however, greatly help if a binary (the `test-reporter-latest`) is uploaded by [creating a release](https://help.github.com/articles/creating-releases/). That way we can just

```shell
curl -L https://github.com/codeclimate/test-reporter/releases/download/alpha/test-reporter
```

**Comment by ale7714** [comment]
@franklinyu hi, I just updated our [README](https://github.com/codeclimate/test-reporter#installation--usage) to point to a link where you can get the latest binary for now.

**Comment by franklinyu** [comment]
@ale7714 In the README the workflow is `before-build` and `after-build`, which is not (yet?) available. Is that out of date, or that's the desired but not-yet-implemented workflow? I guess they belongs to the TODO in [high-level commands](https://github.com/codeclimate/test-reporter/blob/master/man/cc-test-reporter.1.md#high-level-commands).

In addition, I tried low-level command `upload-coverage`; it requires an ID, but I can't find any ID in my settings page. The closest thing I can find is a "test reporter token"; `upload-coverage` with the token gives me [400](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1) from https://codeclimate.com/test_reports.

**Comment by ale7714** [comment]
Yes, the high level commands are still under implementation. For now, you can use the low level commands: 
```
cc_test_reporter format-coverage 
cc_test_reporter upload-coverage -r <test_report_token> 
```

You can pass a -d to get debug output

**Comment by franklinyu** [comment]
@ale7714 passing `-d` gives me

```text
Error: unknown shorthand flag: 'd' in -d
```

**Comment by ale7714** [comment]
I'll take a look into this and write back when I have more info.  Thanks for trying it.

**Comment by ale7714** [comment]
@franklinyu 👋  sorry the late follow up on this. Just wanted to update update you on how to get the binaries 
- latest will always point to our latest stable release 
   ```
      https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 
      https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 
    ```
- specific version binary is available at `https://codeclimate.com/downloads/test-reporter/test-reporter-<version>-darwin-amd64`. For example, if you want the binary for the release v0.1.10 you will use the replace `<version>` with the version number `0.1.10`
   ```
      https://codeclimate.com/downloads/test-reporter/test-reporter-0.1.10-linux-amd64 
      https://codeclimate.com/downloads/test-reporter/test-reporter-0.1.10-darwin-amd64 
    ```

I'll close the issue for now but feel free to reopen if you need to.

**Comment by franklinyu** [comment]
Thanks a lot! That download address looks much better than the S3 one. In addition, the high-level commands finally works! 🎉 

1. Is this command-line utility is stable now? It now reads the reporter ID from `$CC_TEST_REPORTER_ID`, which used to be `$CODECLIMATE_REPO_TOKEN`. If this will be the final decision in foreseeable future, I may try to discuss with SemaphoreCI (my CI provider) about changing their settings (maybe keeping both variables during transition).
2. The manual pages looks like they are written in [troff](https://en.wikipedia.org/wiki/Troff). Are the source file of these manual pages available? That way I can look them up in my local machine.
3. How about the SimpleCov-formatter idea mentioned in codeclimate/ruby-test-reporter#181?

<sub>Hint: I don’t mean to re-open this issue (since it’s already fixed), but I can only reopen an issue that I closed myself (this is how GitHub works). So typically if issue submitters needed to re-open it, they comment to ask for reopening. I have been misled before. 😄 </sub>
